export interface ChecklistQuestion {
    id: string;
    text: string;
    area: string;
}

export const AUDIT_TEMPLATES: Record<string, ChecklistQuestion[]> = {
    il: [
        { id: "il_q1", text: "Bir önceki Cevaplı Teftiş Raporunun \"Tenkit\" bölümündeki maddelerin İl Müdürlüğünce yerine getirilme durumu kontrol edilmiş mi?", area: "Önceki Denetim" },
        { id: "il_q2", text: "Son Mütalaa metninde öneri getirildiği halde yerine getirilmeyen hususlar maddeler halinde raporlanmış mı?", area: "Önceki Denetim" },
        { id: "il_q3", text: "Bir önceki teftiş raporu, rapora ilişkin tüm yazışmalar ve arşiv belgeleri eksiksiz şekilde muhafaza ediliyor mu?", area: "Önceki Denetim" },
        { id: "il_q4", text: "Teftiş raporunda yer alan tenkit/öneriler ile Genel Müdürlük son mütalaasına en geç (15) gün içinde cevap verilmiş mi?", area: "Önceki Denetim" },
        { id: "il_q5", text: "Son üç yılın yeni ve vizeli sporcu sayıları (kız/erkek) mukayese edilerek sporcu sayılarında azalma olup olmadığı denetlenmiş mi?", area: "Spor Faaliyetleri" },
        { id: "il_q6", text: "Tescilli kulüpler, branşları, milli sporcu sayıları, uluslararası ve ulusal derece alan sporcu ve takım istatistikleri güncel mi?", area: "Spor Faaliyetleri" },
        { id: "il_q7", text: "İl Spor Merkezlerine branşlarına göre katılan sporcu sayıları, devam çizelgeleri ve kayıt işlemleri düzenli tutuluyor mu?", area: "Spor Faaliyetleri" },
        { id: "il_q8", text: "Fahri antrenörlerin ve hizmet satın alımıyla görevlendirilenlerin antrenörlük belgeleri ve BESYO diplomaları tam mı?", area: "Spor Faaliyetleri" },
        { id: "il_q9", text: "İl Spor Merkezleri antrenörleri için branş bazında ücret tespiti yapılarak il başkanlığından gerekli onaylar alınmış mı?", area: "Spor Faaliyetleri" },
        { id: "il_q10", text: "Antrenörlerin \"Antrenörlerin Çalışma Esas ve Usulleri Yönergesi\"ne uygun çalışıp çalışmadıkları ve mesai saatlerindeki ek ücretleri denetlenmiş mi?", area: "Spor Faaliyetleri" },
        { id: "il_q11", text: "İl Spor Merkezlerine katılımı artırıcı özendirici çalışmalar (afiş, ilan, duyuru, radyo anonsu, okul tanıtımları vb.) yapılıyor mu?", area: "Spor Faaliyetleri" },
        { id: "il_q12", text: "Branş ve kategorilere göre faal hakem sayılarının yeterliliği kontrol edilerek eksik branşlar için kurs talebinde bulunulmuş mu?", area: "Spor Faaliyetleri" },
        { id: "il_q13", text: "Salon sporlarında liglerin düzenlenip düzenlenmediği ve diğer branşlarda il birinciliği müsabakalarının yapılıp yapılmadığı kontrol edilmiş mi?", area: "Spor Faaliyetleri" },
        { id: "il_q14", text: "Spor Dalı Temsilcilerinin yönetmeliğe uygun atanıp atanmadığı ve yıllık faaliyet programlarının federasyonlarca tasdiki yapılmış mı?", area: "Spor Faaliyetleri" },
        { id: "il_q15", text: "Stadyum atletizm pistlerinin sabah erken ve akşam saatlerinde halkın kullanımına açık bulundurulması sağlanıyor mu?", area: "Spor Faaliyetleri" },
        { id: "il_q16", text: "Okul spor faaliyetleri ve okul-üniversite-il müdürlüğü ilişkileri (tesis, antrenör, malzeme paylaşımı) mevzuata uygun mu?", area: "Spor Faaliyetleri" },
        { id: "il_q17", text: "Gençlik Merkezi çalışmaları için İl Müdürlüğünce uygun, yeterli ve güvenli bir fiziki yer sağlanıp sağlanmadığı kontrol edilmiş mi?", area: "Gençlik Hizmetleri" },
        { id: "il_q18", text: "Gençlik Hizmetlerinde çalışan gençlik liderleri ve eğiticilerin sayı ve nitelik yönünden yeterliliği denetlenmiş mi?", area: "Gençlik Hizmetleri" },
        { id: "il_q19", text: "Gençlik Merkezlerinde üye kayıt defterinin tutulma durumu ile oluşturulan branşlardaki genç katılım sayıları uygun mu?", area: "Gençlik Hizmetleri" },
        { id: "il_q20", text: "Gençlik Merkezlerinde içki, sigara ve uyuşturucu gibi zararlı alışkanlıklarla mücadeleye yönelik çalışmalar yapılıyor mu?", area: "Gençlik Hizmetleri" },
        { id: "il_q21", text: "Gençlik kampları için Genel Müdürlükçe gönderilen ödeneklerin harcamaları mevzuata ve amacına uygun olarak yapılmış mı?", area: "Gençlik Hizmetleri" },
        { id: "il_q22", text: "İller arası ve uluslararası değişim programlarında, misafir gelen genç sayısı kadar ilden genç görevlendirilmesi kuralına uyuluyor mu?", area: "Gençlik Hizmetleri" },
        { id: "il_q23", text: "Mülkiyeti Genel Müdürlüğe ait spor tesisleri, arsalar ve intifa hakkı alınan/devredilen taşınmazların listesi güncel mi?", area: "Tesisler ve Arsalar" },
        { id: "il_q24", text: "Tesislerin yerinde denetimi yapılarak; bakım, onarım ve boya işleri için yapılan harcamalar yerinde incelenmiş mi?", area: "Tesisler ve Arsalar" },
        { id: "il_q25", text: "Yangın tehlikesi olan tüm tesislerde yangın söndürme tüplerinin varlığı ve dolum/son kullanma tarihleri güncel mi?", area: "Tesisler ve Arsalar" },
        { id: "il_q26", text: "Hizmet binalarının dış görünümü, çevre düzeni ve personel için uygun çalışma ortamı şartları sağlanmış mı?", area: "Tesisler ve Arsalar" },
        { id: "il_q27", text: "Spor salonlarının parke/zemini, çatı sızdırmazlığı, ısıtma, aydınlatma, cam kırıkları, sıva döküntüleri ve temizliği uygun mu?", area: "Tesisler ve Arsalar" },
        { id: "il_q28", text: "Spor salonlarının inşaat, yapım ve büyük tamir sicil dosyaları düzenli tutulup bir örneği Genel Müdürlüğe gönderilmiş mi?", area: "Tesisler ve Arsalar" },
        { id: "il_q29", text: "Stad ve futbol sahalarının çim/suni çim durumu, haşereyle mücadele, drenaj sistemi ve tribün bakımları yeterli mi?", area: "Tesisler ve Arsalar" },
        { id: "il_q30", text: "Yüzme havuzlarının klorlama ölçümleri, numune su tahlil kayıtları, filtrasyon sistemleri ve cankurtaran görevlendirmesi tam mı?", area: "Tesisler ve Arsalar" },
        { id: "il_q31", text: "Yüzme havuzlarının su ve ortam sıcaklığı, havuz yalıtımı, yakıt giderlerinin optimizasyonu ve havuz gelirleri kontrol edilmiş mi?", area: "Tesisler ve Arsalar" },
        { id: "il_q32", text: "Kamp Eğitim Merkezleri ve misafirhanelerin temizliği, duş/tuvalet sistemleri, demirbaş listeleri ve konaklama defterleri uygun mu?", area: "Tesisler ve Arsalar" },
        { id: "il_q33", text: "Kamp yemekhanelerinde malzeme alım/muayene komisyonları kurulmuş mu, ambar defteri tutuluyor mu ve mönüler diyetisyen onaylı mı?", area: "Tesisler ve Arsalar" },
        { id: "il_q34", text: "Sporcu Eğitim Merkezlerinde sporcu gelişimi, kadro yeterliliği ve çocukların seçiminde elit sporcu kriterlerine uyuluyor mu?", area: "Tesisler ve Arsalar" },
        { id: "il_q35", text: "Özel Beden Eğitimi ve Spor Tesislerinin tescil kayıtları, denetimleri ve amacı dışında (siyasi vb.) faaliyet kontrolleri yapılıyor mu?", area: "Tesisler ve Arsalar" },
        { id: "il_q36", text: "Mevcut arsaların metrekare and mevki bilgileri kontrol edilerek, ihtiyaç duyulan arsalar için İl Müdürlüğünce resmi girişimler yapılmış mı?", area: "Tesisler ve Arsalar" },
        { id: "il_q37", text: "Defterlerin Taşra Teşkilatı Muhasebe Uygulama Talimatı kurallarına uygun olarak tutulup tutulmadığı denetlenmiş mi?", area: "Mali İşlemler" },
        { id: "il_q38", text: "Esas Defter ile Banka Defteri mutabakatı yapılarak, teftişin bittiği gün itibariyle sahife yekünleri farkı deftere işlenmiş mi?", area: "Mali İşlemler" },
        { id: "il_q39", text: "Banka mevcutları (vadeli/vadesiz), çekilmeyen çekler ve bankaya yatıp kayıtlara girmeyen gelirlerin denklik tespiti yapılarak mühürlenmiş mi?", area: "Mali İşlemler" },
        { id: "il_q40", text: "B.M.B. Yönetmeliği uyarınca muhasebeci ve muhasebeden sorumlu şube müdürlerinin devir-teslim işlemleri kontrol edilmiş mi?", area: "Mali İşlemler" },
        { id: "il_q41", text: "Emanet Defteri kayıtlarındaki emekli keseneği, gelir vergisi, damga vergisi ve federasyon payları zamanında ödenmiş mi?", area: "Mali İşlemler" },
        { id: "il_q42", text: "Emanet hesaplarından yasal sınırdan fazla veya usulsüz reddiyat (ceza, faiz ödemesi gibi) yapılıp yapılmadığı denetlenmiş mi?", area: "Mali İşlemler" },
        { id: "il_q43", text: "Emanet hesaplarında zamanaşımına uğrayan tutarlar yasal süresi sonunda Bütçe Geliri hesabına aktarılmış mı?", area: "Mali İşlemler" },
        { id: "il_q44", text: "İlgililere dağıtılmak üzere mutemede verilen ancak uzun süre dağıtılmayan paraların akıbeti kontrol edilmiş mi?", area: "Mali İşlemler" },
        { id: "il_q45", text: "İl Müdürlüğünce yapılan fazla ödemeler ve tahsil edilemeyen bütçe/kira gelirleri \"Borçlular Hesabı\"na alınarak takip ediliyor mu?", area: "Mali İşlemler" },
        { id: "il_q46", text: "Borçlular hesabına alınan alacaklardan zamanaşımına uğratılanlar varsa Borçlar Kanununa göre sorumlulardan tahsil ediliyor mu?", area: "Mali İşlemler" },
        { id: "il_q47", text: "Gelir Fişleri müteselsil sıra numarasına göre tanzim ediliyor mu, kanıtlayıcı belgeler ekli mi ve yetkili imzaları tam mı?", area: "Mali İşlemler" },
        { id: "il_q48", text: "Genel Müdürlükten gönderilen nakitlerin İl Müdürlüğü hesabına geçirilme kayıtları Genel Müdürlük verileriyle karşılaştırılmış mı?", area: "Mali İşlemler" },
        { id: "il_q49", text: "Satılan müsabaka bilet bedellerinin takip eden ilk iş günü bankaya yatırılması ve Hasılat Dağıtım Yönetmeliğine göre paylaştırılması uygun mu?", area: "Mali İşlemler" },
        { id: "il_q50", text: "Tesis tahsislerinde talep dilekçesi alınmış mı, 4 nüsha sözleşme yapılmış mı ve %6 teminat ile KDV dahil ücretler bankaya yatmış mı?", area: "Mali İşlemler" },
        { id: "il_q51", text: "Tesis hasarları durumunda gerekli hasar tutanakları düzenlenerek hasar bedeli ilgililerden tahsil edilmiş mi?", area: "Mali İşlemler" },
        { id: "il_q52", text: "Antrenman tahsislerinde sözleşme yapılması, antrenman saatlerinin deftere kaydı ve %5 pay kesintileri usulüne uygun mu?", area: "Mali İşlemler" },
        { id: "il_q53", text: "Reklam sözleşmelerinin yapılması, panoların uyumu, bedellerin tahsili, %5 pay alımı ve süresi dolan reklamların kaldırılması denetlenmiş mi?", area: "Mali İşlemler" },
        { id: "il_q54", text: "Reklamların toplu pazarlanmasında ihale mevzuatına uyulmuş mu ve bedellerin Bütçe Geliri Hesabında takibi yapılıyor mu?", area: "Mali İşlemler" },
        { id: "il_q55", text: "Misafirhane ve Kamp Eğitim Merkezi konaklama defterleri, kimlik bildirim kayıtları ve ücretlerin bankaya yatırılması kontrol edilmiş mi?", area: "Mali İşlemler" },
        { id: "il_q56", text: "Büfe, arsa, bina ve lokal kiralamalarında ihale işlemlerinin B.İ.M.B. Yönetmeliği ve Maliye Bakanlığı genelgelerine uygunluğu denetlenmiş mi?", area: "Mali İşlemler" },
        { id: "il_q57", text: "Kira ihalelerinde muhammen bedel tespiti, ilan süresi, geçici/kesin teminatlar ve ihale kararının İl Başkanınca 15 günde onayı yapılmış mı?", area: "Mali İşlemler" },
        { id: "il_q58", text: "Kira ödemelerinde taksit/peşin kurallarına uyuluyor mu, gecikme durumunda ihtarname çekilip yasal işlem başlatılıyor mu?", area: "Mali İşlemler" },
        { id: "il_q59", text: "Lojman kira ve yakıt bedellerinin Kamu Konutları Yönetmeliğine uygun tahsili ile kaloriferci/otomat/su gider paylaşımı doğru mu?", area: "Mali İşlemler" },
        { id: "il_q60", text: "Teleski, telesiyej ve otopark gelirlerinin tespiti, kayıtları, bankaya yatırılması ve Vakıf/Kurum paylarının dağıtımı mevzuata uygun mu?", area: "Mali İşlemler" },
        { id: "il_q61", text: "Kavak, hurda, fıstık çamı vb. arızi satış gelirlerinin piyasa araştırması yapılarak tutanakla belgelendirilmesi sağlanmış mı?", area: "Mali İşlemler" },
        { id: "il_q62", text: "Gider Fişlerinin müteselsil sıra no takibi, bütçe ödenek uygunluğu, muhasebeci ve müdür imzaları ile ek belgeleri tam mı?", area: "Mali İşlemler" },
        { id: "il_q63", text: "Malzeme alımı ihalelerinde onay belgesi, yaklaşık maliyet tespiti, en az 5 kişilik ihale komisyonu kurulumu ve ilan işlemleri uygun mu?", area: "Mali İşlemler" },
        { id: "il_q64", text: "İhalelerde en avantajlı iki teklifin belirlenmesi, 20 günde karar onayı, notere tasdikli sözleşme ve 3 kişilik muayene komisyonu işlemleri tam mı?", area: "Mali İşlemler" },
        { id: "il_q65", text: "Doğrudan temin alımlarında piyasa araştırması için personel görevlendirilmesi yapılmış mı ve parasal limit eşiklerine uyuluyor mu?", area: "Mali İşlemler" },
        { id: "il_q66", text: "Yapılan bakım ve onarım işlerinin hakediş raporları ile sahada fiilen tamamlanan imalatlar yerinde karşılaştırılmış mı?", area: "Mali İşlemler" },
        { id: "il_q67", text: "Yakacak (kömür, akaryakıt vb.) alımlarında kamyonların boş/dolu tartılması, tartıda personel bulunması ve teslim alma tutanakları düzenli mi?", area: "Mali İşlemler" },
        { id: "il_q68", text: "Personel maaş, kıdem zammı, tazminat bordroları, emekli kesenekleri ve yasal vergi tevkifatları doğru hesaplanıyor mu?", area: "Mali İşlemler" },
        { id: "il_q69", text: "Müsabaka görev ücreti bordroları, görev onayları, personel çakışma (aynı saatte çift görev) kontrolleri ve vergi matrahı işlemleri uygun mu?", area: "Mali İşlemler" },
        { id: "il_q70", text: "Yolluk ve harcırah ödemelerinde avans mahsup sürelerine (B.İ.M.B. uyarınca) uyuluyor mu ve fazla ödemelerin önüne geçilmiş mi?", area: "Mali İşlemler" },
        { id: "il_q71", text: "Tedavi giderlerinde (hastane sevk, reçete, ilaç kupür/barkod iptali) 4 kalem ilaç sınırı ve 10 günlük doz kurallarına uyuluyor mu?", area: "Mali İşlemler" },
        { id: "il_q72", text: "Gözlük çerçevesinin 2 yıldan önce verilmemesi, cam bedellerinin bütçe limitlerine uygunluğu ve diş tedavi sevk onayları tam mı?", area: "Mali İşlemler" },
        { id: "il_q73", text: "Memur giyecek yardımı ihalelerinin usulü ile Toplu İş Sözleşmesi gereği işçilere verilecek giysilerin imza mukabili dağıtımı yapılmış mı?", area: "Mali İşlemler" },
        { id: "il_q74", text: "Mutemet makbuzlarının müteselsil numaralı basımı, dip koçanlarının saklanması ve paraların en geç ertesi iş günü bankaya yatırılması uygun mu?", area: "Mali İşlemler" },
        { id: "il_q75", text: "Mutemet eliyle tahsilat limitlerine uyuluyor mu ve son makbuzun arkasına banka dekontu ekleniyor mu?", area: "Mali İşlemler" },
        { id: "il_q76", text: "Avans alımlarında belirlenen limitlere uyuluyor mu ve avans kapatma sürelerine (mutemet 4 hafta, spor 10 gün, tedavi 15 gün) uyuluyor mu?", area: "Mali İşlemler" },
        { id: "il_q77", text: "Satın alınan veya hibe edilen demirbaş ve tüketim malzemeleri için Taşınır Mal İşlem Fişi (TİF) düzenlenip ambar sayımları yapılıyor mu?", area: "İdari İşlemler" },
        { id: "il_q78", text: "Personel izin-rapor kartları, özlük dosyaları (iyi hal, sağlık raporu, mal bildirimi vb.) SGK aylık prim tahakkukları güncel mi?", area: "İdari İşlemler" },
        { id: "il_q79", text: "Personelin kılık kıyafet yönetmeliği, etik sözleşmesi imzaları, mesai saatleri ve şube müdürlerinin Valilik Oluru görev dağılımları uygun mu?", area: "İdari İşlemler" },
        { id: "il_q80", text: "Gelen/giden evrakların doğrudan kayda girmesi, zimmet defteri kayıtları ve evrakların Arşiv Yönetmeliğine göre dosyalanması uygun mu?", area: "İdari İşlemler" }
    ],
    federasyon: [
        // ═══ 1) KURULUŞ ve TEŞKİLAT (7405 sayılı Kanun) ═══
        { id: "fed_q1", text: "Federasyonun ana statüsü güncel mi ve Resmi Gazete'de yayımlanmış mı? Bakanlık uygun görüşüyle yapılan değişiklikler tamamlanmış mı?", area: "Kuruluş ve Teşkilat" },
        { id: "fed_q2", text: "Federasyon merkez teşkilatı; genel kurul, yönetim kurulu, denetim kurulu, disiplin kurulu ve genel sekreterlikten oluşuyor mu?", area: "Kuruluş ve Teşkilat" },
        { id: "fed_q3", text: "Federasyonun yıllık ve dört yıllık stratejik planı hazırlanmış ve Bakanlığa sunulmuş mu?", area: "Kuruluş ve Teşkilat" },
        { id: "fed_q4", text: "İl temsilcilikleri kurulması teklifi Bakanlık onayına sunulmak üzere Genel Müdürlüğe iletilmiş mi?", area: "Kuruluş ve Teşkilat" },
        { id: "fed_q5", text: "Federasyonun iş ve işlemleri Bakanlık bilişim sistemleri üzerinden yürütülüyor mu?", area: "Kuruluş ve Teşkilat" },
        { id: "fed_q6", text: "Spor dalının ülke genelinde yaygınlaştırılması ve her yaş grubunda yapılması için çalışmalar yürütülüyor mu?", area: "Kuruluş ve Teşkilat" },
        // ═══ 2) GENEL KURUL ═══
        { id: "fed_q7", text: "Genel kurul toplantısına ilişkin duyuru, gündem ve çağrı işlemleri mevzuata uygun yapılmış mı? Toplantı tutanakları eksiksiz mi?", area: "Genel Kurul" },
        { id: "fed_q8", text: "Genel kurulda bütçe onayı yapılmış mı? Bütçe harcama kalemleri arasındaki değişiklikler için yönetim kuruluna yetki verilmiş mi?", area: "Genel Kurul" },
        { id: "fed_q9", text: "Yönetim kurulu faaliyet raporu ile denetim kurulu raporu genel kurulda ibra oylamasına sunulmuş mu?", area: "Genel Kurul" },
        { id: "fed_q10", text: "Taşınmaz alım satımı ve uluslararası spor federasyonlarına karşı mali taahhütler için genel kuruldan yönetim kuruluna yetki verilmiş mi?", area: "Genel Kurul" },
        { id: "fed_q11", text: "İktisadi işletme kurulmasına genel kurulda karar alınmış mı? Ana statüde çalışma usul ve esasları belirlenmiş mi?", area: "Genel Kurul" },
        { id: "fed_q12", text: "Ödül ve yardım talimatı genel kurulca onaylanmış mı? Talimat, Spor Hizmet ve Faaliyetlerinde Üstün Başarı Gösterenlerin Ödüllendirilmesi Yönetmeliği ile uyumlu mu?", area: "Genel Kurul" },
        // ═══ 3) YÖNETİM KURULU ═══
        { id: "fed_q13", text: "Yönetim kurulu en az üç ayda bir toplanıyor mu? Toplantı tutanakları noter tasdikli karar defterine işlenmiş mi?", area: "Yönetim Kurulu" },
        { id: "fed_q14", text: "Yönetim kurulu kararları, üye tam sayısının salt çoğunluğuyla alınıyor mu? Karara katılmayan üyelerin görüşleri tutanağa yansımış mı?", area: "Yönetim Kurulu" },
        { id: "fed_q15", text: "Üst üste iki veya iki yılda toplam dört toplantıya mazeretsiz katılmayan üyelerin üyeliğinin kendiliğinden sona erdiğine dair işlem yapılmış mı?", area: "Yönetim Kurulu" },
        { id: "fed_q16", text: "Elektronik ortamda yapılan toplantılar Bakanlık bilişim sistemleri üzerinden mi gerçekleştiriliyor? Kimlik doğrulama faktörleri kullanılıyor mu?", area: "Yönetim Kurulu" },
        { id: "fed_q17", text: "Yönetim kurulu kararlarında; konu, yer, zaman, yetkili kişilerin kimlikleri, harcama tutarı ve alım yöntemi tereddüte yer vermeyecek şekilde detaylı hazırlanmış mı?", area: "Yönetim Kurulu" },
        { id: "fed_q18", text: "Rutin veya küçük meblağlı harcamalar hariç, tüm faaliyet ve harcamalar ayrı bir yönetim kurulu kararına bağlanmış mı?", area: "Yönetim Kurulu" },
        { id: "fed_q19", text: "Harcama yetkilileri ve harcama limitleri her yıl yönetim kurulu tarafından belirlenerek yayımlanmış mı?", area: "Yönetim Kurulu" },
        // ═══ 4) DENETİM KURULU ═══
        { id: "fed_q20", text: "Denetim kurulu, mali yılda en az dört kez (üçer aylık dönemler halinde) toplantı yapıyor mu? Denetim tutanakları yönetim kuruluna bildiriliyor mu?", area: "Denetim Kurulu" },
        { id: "fed_q21", text: "Denetim kurulu yıllık denetim raporu hazırlanarak genel kurulun onayına sunuluyor mu?", area: "Denetim Kurulu" },
        { id: "fed_q22", text: "Denetim kurulunun tespit ettiği eksikliklerin yönetim kurulunca giderildiği takip ediliyor mu? Giderilmeyenler genel kurul raporuna yansıtılmış mı?", area: "Denetim Kurulu" },
        { id: "fed_q23", text: "Denetim kurulu üyelerinde aranan şartlar (vatandaşlık, en az lise mezuniyeti, adli sicil temizliği, hak mahrumiyeti yokluğu) sağlanıyor mu?", area: "Denetim Kurulu" },
        { id: "fed_q24", text: "Denetimlerin federasyon merkezinde yapılması zorunluluğuna uyuluyor mu?", area: "Denetim Kurulu" },
        // ═══ 5) BAŞKANLIK ve ORGANLAR ═══
        { id: "fed_q25", text: "Federasyon başkanının aynı federasyonda üst üste veya aralıklı en fazla üç dönem görev yapma sınırına uyuluyor mu?", area: "Başkanlık ve Organlar" },
        { id: "fed_q26", text: "Federasyon başkanı adaylık başvurusunda; TC kimlik belgesi, öğrenim belgesi, adli sicil, hak mahrumiyeti beyanı ve delegelerin en az %10 yazılı desteği sunulmuş mu?", area: "Başkanlık ve Organlar" },
        { id: "fed_q27", text: "Federasyonda ücretli veya fahri görev alanların, bağlı spor dallarındaki spor kulübü üyelik ve yöneticiliklerinin görevle birlikte sona erdiği kontrol edilmiş mi?", area: "Başkanlık ve Organlar" },
        { id: "fed_q28", text: "Disiplin kuruluna sevk işlemleri federasyon başkanı tarafından usulüne uygun yapılıyor mu?", area: "Başkanlık ve Organlar" },
        { id: "fed_q29", text: "Genel sekreter; yönetim kurulu toplantılarına katılıyor mu, kararların yazılması dahil sekreterya işlerini yürütüyor mu? (Oy hakkı yok)", area: "Başkanlık ve Organlar" },
        // ═══ 6) MUHASEBE GÖREVLİSİ (Yönerge Eki A - Madde 1) ═══
        { id: "fed_q30", text: "Federasyonda muhasebe görevlisi atanmış mı? Muhasebe görevlisinin görev, yetki ve sorumlulukları yazılı olarak belirlenmiş mi?", area: "Muhasebe Görevlisi" },
        { id: "fed_q31", text: "Muhasebe görevlisi; federasyon muhasebesini genel muhasebe uygulama ve tebliğleri çerçevesinde tutuyor mu?", area: "Muhasebe Görevlisi" },
        { id: "fed_q32", text: "Gün, ay ve yıl sonu işlem ve mutabakatları yapılıyor mu? Mali tablo ve raporlar süresinde ve doğru düzenleniyor mu?", area: "Muhasebe Görevlisi" },
        { id: "fed_q33", text: "Kayıtlara ilişkin her türlü defter, bilgi ve belgeler düzenli saklanıp her an denetime hazır halde bulunduruluyor mu?", area: "Muhasebe Görevlisi" },
        { id: "fed_q34", text: "Muhasebe görevlisi, MİM'e gönderilecek bilgileri zamanında ve aksaksız gönderiyor mu?", area: "Muhasebe Görevlisi" },
        { id: "fed_q35", text: "Avans ödemeleri kişi, faaliyet veya işlem bazında takip ediliyor mu? Süresinde kapatılmayanlar için gecikme faizi hesaplanıyor mu?", area: "Muhasebe Görevlisi" },
        // ═══ 7) MUHASEBE FİŞLERİ (Yönerge Eki A - Madde 2) ═══
        { id: "fed_q36", text: "Hesaplarda azalmaya/artmaya neden olan her işlem muhasebe fişine (Gelir Fişi, Gider Fişi, Mahsup Fişi) dayanıyor mu?", area: "Muhasebe Fişleri" },
        { id: "fed_q37", text: "Gün içinde kesilen fişler belli bir seri numarasını takip ediyor mu? Tarih, saat ve düzenleyenin isim/rumuzunu içeriyor mu?", area: "Muhasebe Fişleri" },
        { id: "fed_q38", text: "Fişlerde, düzenleyen muhasebe görevlisi ile federasyon başkanı veya yazılı yetkilendirdiği kişilerin imzası var mı?", area: "Muhasebe Fişleri" },
        { id: "fed_q39", text: "Fiş ekinde, işlemle ilgili kanıtlayıcı ve açıklayıcı evrak bulunuyor mu?", area: "Muhasebe Fişleri" },
        // ═══ 8) HARCAMA YETKİLİLERİ (Yönerge Eki A - Madde 3) ═══
        { id: "fed_q40", text: "Harcama belgelerinde, genel sekreterin yanında federasyon başkanı veya başkan vekilinin imzası bulunuyor mu?", area: "Harcama Yetkilileri" },
        { id: "fed_q41", text: "İmzaları eksik veya yetkisiz yapılan harcamalar tespit edilmiş mi? İmza ikmallerinin yapılamadığı durumlarda harcamalar kişisel borç olarak takip ediliyor mu?", area: "Harcama Yetkilileri" },
        // ═══ 9) GELİRLER - GM YARDIMLARI (Yönerge Eki A - Madde 4) ═══
        { id: "fed_q42", text: "Genel Müdürlük yardımları tahsis amacı dışında kullanılmıyor mu? Bütçeden aktarılan paylar sadece altyapı ve eğitim harcamalarında mı harcanıyor?", area: "Gelirler" },
        { id: "fed_q43", text: "Teknik personel ve sporcular hariç, federasyon personel ücretleri kamu kaynakları ve Spor Toto reklam gelirlerinden karşılanmıyor mu?", area: "Gelirler" },
        { id: "fed_q44", text: "Genel Müdürlükçe yapılan ayni ve nakdi yardımların mevzuata/amacına uygun harcanması denetleniyor mu? Aykırı harcamalarda zarar ilgililerden tahsil ediliyor mu?", area: "Gelirler" },
        { id: "fed_q45", text: "Altyapı ve eğitim projeleri için aktarılan kaynaklar proje ismi ve yer belirtilerek tahsis ediliyor mu? Proje ödenekleri sadece tahsis konusu için harcanıyor mu?", area: "Gelirler" },
        { id: "fed_q46", text: "Proje harcamalarına ait evrak suretleri, proje tamamlanmasını müteakip Spor Faaliyetleri Dairesi Başkanlığına gönderiliyor mu?", area: "Gelirler" },
        // ═══ 10) GELİRLER - DİĞER (Yönerge Eki A - Madde 5) ═══
        { id: "fed_q47", text: "Katılım payı, tescil, vize, transfer, itiraz, ceza, yayın, sponsorluk, reklam, yardım ve bağış gelirleri için ayrı ortak banka hesabı açılmış mı?", area: "Gelirler" },
        { id: "fed_q48", text: "Nakdi gelirlerin banka hesabı üzerinden tahsil edilmesi esas alınıyor mu? Zorunlu hallerde Gelir Alındı Belgeleriyle tahsilat yapılıyorsa yönetim kurulu kararı var mı?", area: "Gelirler" },
        { id: "fed_q49", text: "Ayni sponsorluk, yardım ve promosyonların piyasa rayiç değerlemesi komisyon marifetiyle yapılarak kayıtlara yansıtılmış mı?", area: "Gelirler" },
        { id: "fed_q50", text: "Sponsorluk sözleşme örnekleri her yıl düzenli olarak Genel Müdürlük Spor Kuruluşları Dairesi Başkanlığına gönderiliyor mu?", area: "Gelirler" },
        { id: "fed_q51", text: "Yurt dışından yapılan hibe, yardım ve mali destekler dahil tüm gelirler hesaplara intikal ettirilmiş mi?", area: "Gelirler" },
        { id: "fed_q52", text: "Gelirlerin teminiyle ilgili sözleşmeler, protokoller, yazışmalar ve diğer belgeler dosyalarında muhafaza ediliyor mu?", area: "Gelirler" },
        // ═══ 11) GİDERLER - BANKA (Yönerge Eki A - Madde 6) ═══
        { id: "fed_q53", text: "8.000 TL ve üzerindeki mal/hizmet alım bedeli ödemelerinde banka aracılığı (Vergi Usul Kanunu tebliğleri gereği) kullanılıyor mu?", area: "Giderler" },
        { id: "fed_q54", text: "8.000 TL altındaki ödemelerde de ispat ve takip kolaylığı açısından banka yöntemi benimseniyor mu?", area: "Giderler" },
        // ═══ 12) AVANSLAR (Yönerge Eki A - Madde 7) ═══
        { id: "fed_q55", text: "Avanslar, tahmini toplam giderin azami %10 fazlasını aşmayacak tutarda ve banka hesabı üzerinden veriliyor mu?", area: "Avanslar" },
        { id: "fed_q56", text: "Avans hesapları, işlem bitiminden itibaren en geç 5 iş günü içinde kapatılıyor mu? Gecikenlerde yönetim kurulu kararıyla gecikme faizi tahsil ediliyor mu?", area: "Avanslar" },
        { id: "fed_q57", text: "Bir avans hesabı kapatılmadan yeni avans açılmamış mı? (Zorunlu durumlar yönetim kurulu kararına bağlanıyor mu?)", area: "Avanslar" },
        { id: "fed_q58", text: "Her avans için başkanlık onayı alınıyor mu? Kime, ne kadar, hangi iş için verildiği onay belgesinde yazılı mı?", area: "Avanslar" },
        { id: "fed_q59", text: "Federasyon başkanı, asbaşkanlar ve yönetim kurulu üyeleri hariç kişilere toplam 20.000 TL'yi aşan avans verilmemiş mi? Bir kişiye tek seferde 100.000 TL'yi aşan avans verilmemiş mi?", area: "Avanslar" },
        { id: "fed_q60", text: "Avansın veriliş tarihinden önce yapılmış giderlerin avans hesabından karşılanmadığı kontrol edilmiş mi?", area: "Avanslar" },
        // ═══ 13) MAL VE HİZMET ALIMLARI (Yönerge Eki A - Madde 8) ═══
        { id: "fed_q61", text: "Mal ve hizmet alımlarında belirlenmiş parasal limitlerde piyasa araştırması yapılıyor mu? Araştırma tutanakları dosyalanmış mı?", area: "Mal ve Hizmet Alımları" },
        { id: "fed_q62", text: "Alım yapılan mal/hizmetin sayı ve kalite yönünden uygunluk tespiti (rapor/tutanak) görevlendirilen kişilerce yapılmış mı?", area: "Mal ve Hizmet Alımları" },
        { id: "fed_q63", text: "Alım sözleşmelerinde teknik konular dışındaki hususların eksiksiz yerine getirildiğine dair bilgi ve belgeler mevcut mu?", area: "Mal ve Hizmet Alımları" },
        // ═══ 14) PERSONEL İSTİHDAMI (Yönerge Eki A - Madde 9) ═══
        { id: "fed_q64", text: "Sözleşmeli personel ile yazılı iş sözleşmesi yapılmış mı? Sözleşmede; görev tanımı, süre, çalışma saatleri, ücret, sosyal haklar ve fesih şartları belirtilmiş mi?", area: "Personel" },
        { id: "fed_q65", text: "Personelin SGK bildirgesi süresinde verilmiş mi? SGK primleri düzenli ödeniyor mu?", area: "Personel" },
        { id: "fed_q66", text: "Personel özlük dosyalarında; kimlik, adli sicil, diploma, sağlık raporu ve iş sözleşmesi bulunuyor mu?", area: "Personel" },
        // ═══ 15) HARCIRAH VE GÖREV ÜCRETLERİ (Yönerge Eki A - Madde 10) ═══
        { id: "fed_q67", text: "Harcırah ve görev ücretlerinde kanuni sınırlamalara uyuluyor mu? Aynı faaliyet için farklı unvanlar altında mükerrer ödeme yapılmıyor mu?", area: "Harcırah ve Görev Ücretleri" },
        { id: "fed_q68", text: "Faaliyette fiilen görev yapmayan kişilere herhangi bir ödeme yapılmamış mı?", area: "Harcırah ve Görev Ücretleri" },
        { id: "fed_q69", text: "Yemek ve konaklama (iaşe-ibate) giderlerinin karşılandığı durumlarda ayrıca tam gündelik ödenmemiş mi?", area: "Harcırah ve Görev Ücretleri" },
        { id: "fed_q70", text: "Gündelikle ilgili ödemeler faaliyetin süresiyle ilişkilendirilmiş mi? Faaliyet süresini aşan ödemeler açıklanmış mı?", area: "Harcırah ve Görev Ücretleri" },
        { id: "fed_q71", text: "Toplu seyahatlerde minibüs/otobüs kiralanması tercih ediliyor mu? Otomobil kiralaması zorunlu hallerde, faaliyet mahallinden mi yapılıyor?", area: "Harcırah ve Görev Ücretleri" },
        // ═══ 16) ÖDEME İŞLEMLERİ (Yönerge Eki A - Madde 11) ═══
        { id: "fed_q72", text: "Her ödeme öncesinde; bütçede ödenek yeterliliği, faaliyet programında yer alma durumu, belge hesaplarının doğruluğu kontrol ediliyor mu?", area: "Ödeme İşlemleri" },
        { id: "fed_q73", text: "Başkanlık genel onayı (reglaman), banka ödeme onayı ve ödeme belgesi her harcamada mevcut mu?", area: "Ödeme İşlemleri" },
        { id: "fed_q74", text: "Sözleşmeli personel ücret bordroları; aylık ücreti, fazla mesai, SGK primleri, gelir vergisi stopajı, damga vergisi ve net tutarları içeriyor mu? Bordrolar düzenleyen-kontrol eden-yetkili imzalı mı?", area: "Ödeme İşlemleri" },
        { id: "fed_q75", text: "Harcırah ve görev ücreti ödemeleri; Toplu Görev Ücret Bordrosu veya Toplu Yolluk Bildirimi karşılığında, banka hesabına alacak geçilerek yapılıyor mu?", area: "Ödeme İşlemleri" },
        { id: "fed_q76", text: "Konaklama ödemelerinde; sözleşme/teyitleşme yazısı, detaylı fatura (oda fiyatları, kişi listeleri, giriş-çıkış tarihleri, ekstralar) mevcut mu?", area: "Ödeme İşlemleri" },
        { id: "fed_q77", text: "Alkollü içki bedelleri, faaliyetle bağlantısı olmayan konukların harcamaları, masaj/pay TV gibi kişisel harcamalar ödenmemiş mi?", area: "Ödeme İşlemleri" },
        { id: "fed_q78", text: "Kamplar için puantaj tabloları hazırlanmış mı? Konaklamalarda öncelikle kamp eğitim merkezleri tercih ediliyor mu?", area: "Ödeme İşlemleri" },
        { id: "fed_q79", text: "Uçak biletleri fatura veya orijinal elektronik bilet karşılığında mı ödeniyor? Nakliye/hammaliye ödemelerinde fatura veya gider pusulası alınmış mı?", area: "Ödeme İşlemleri" },
        { id: "fed_q80", text: "Ödül ve yardım ödemelerinde onaylanmış ödül/yardım talimatı mevcut mu? Yapılan yardımlar federasyonun amaç ve faaliyetleriyle örtüşüyor mu?", area: "Ödeme İşlemleri" },
        { id: "fed_q81", text: "Uluslararası kuruluş aidat ödemeleri süresinde yapılıyor mu? Üst kuruluşlardan gelen yazışmalarla miktar/tarih teyit ediliyor mu? SWIFT mesajları dekont ekinde bulunuyor mu?", area: "Ödeme İşlemleri" },
        { id: "fed_q82", text: "Araç kiralama ve yakıt ödemelerinde piyasa fiyat araştırması yapılmış mı? Kiralanan aracın güzergahı, km, yakıt tüketimi ve taşınan kişi/malzeme bilgileri kayıt altında mı?", area: "Ödeme İşlemleri" },
        { id: "fed_q83", text: "Tedavi ve ilaç ödemelerinde doktor reçetesi/yazılı talebi mevcut mu? Reçete yanında ilaç kupürleri ve faturalar temin edilmiş mi?", area: "Ödeme İşlemleri" },
        { id: "fed_q84", text: "Harç pulu ve pasaport bedelleri sadece hizmet damgalı (gri) pasaportlar için mi ödeniyor? Seyahate katılmayanlara yapılan harcamalar geri alınıyor mu?", area: "Ödeme İşlemleri" },
        { id: "fed_q85", text: "Yemek, ağırlama ve ikram ödemelerinde katılımcı listeleri, menü ve detaylı fatura mevcut mu? Faaliyet dışı kişiler için harcama yapılmamış mı?", area: "Ödeme İşlemleri" },
        { id: "fed_q86", text: "Kurul toplantılarında konaklama yapılıyorsa öncelikle resmi kurum tesisleri tercih ediliyor mu? Günlük konaklama gideri, günlük harcırah yevmiyesinin 3 katını geçmiyor mu?", area: "Ödeme İşlemleri" },
        // ═══ 17) VERGİ ve MUHASEBE (Yönerge Eki A - Madde 12-13) ═══
        { id: "fed_q87", text: "SGK prim bildirgeleri, muhtasar beyanname, damga vergisi beyannamesi ve KDV beyannamesi süresinde veriliyor mu?", area: "Vergi ve Muhasebe" },
        { id: "fed_q88", text: "Federasyonun muhasebe uygulamaları Tek Düzen Hesap Planına uygun mu? Gelir-gider tablosu ve bilanço düzenli hazırlanıyor mu?", area: "Vergi ve Muhasebe" },
        // ═══ 18) MALİ ONAY (Yönerge Eki A - Madde 14) ═══
        { id: "fed_q89", text: "Her faaliyet öncesi genel mali onay (reglaman) hazırlanmış mı? Reglaman; faaliyet adı, yeri, tarihi, görevli listesi, tahmini bütçe ve harcama kalemlerini içeriyor mu?", area: "Mali Onay" },
        { id: "fed_q90", text: "Reglaman dışı acil harcamalar için gerekçeli yönetim kurulu kararı alınmış mı?", area: "Mali Onay" },
        // ═══ 19) YURT DIŞI FAALİYETLER (Yönerge Eki A - Madde 15) ═══
        { id: "fed_q91", text: "Yurt dışı faaliyetlerde görevlilerin vize işlemleri zamanında yapılmış mı? Hizmet pasaportu temdit/temin işlemleri tamamlanmış mı?", area: "Yurt Dışı Faaliyetler" },
        { id: "fed_q92", text: "Yurt dışı faaliyetler için ayrıca münferit mali onay hazırlanmış mı? Zaruri/temsil harcaması yapılacaksa gerekçe ve limitler belirtilmiş mi?", area: "Yurt Dışı Faaliyetler" },
        { id: "fed_q93", text: "Yurt dışı çıkışlarda döviz alış belgeleri ve artan döviz iade (satış) belgelerinin muhafaza ediliyor mu? Kur farkları açıkça belirtiliyor mu?", area: "Yurt Dışı Faaliyetler" },
        // ═══ 20) MİM - MUHASEBE İZLEME MERKEZİ (Yönerge Eki A - Madde 16) ═══
        { id: "fed_q94", text: "MİM'e gönderilmesi gereken mizan, gelir-gider tablosu ve bilanço bilgileri düzenli ve zamanında iletiliyor mu?", area: "Muhasebe İzleme" },
        { id: "fed_q95", text: "MİM'in yazılı uyarılarına rağmen gerekli bilgileri vermeyen veya tedbirleri almayan federasyon yetkilileri hakkında cezai işlem yapılmış mı?", area: "Muhasebe İzleme" },
        // ═══ 21) DEFTERLER VE KAYITLAR (Yönerge Eki A - Madde 17) ═══
        { id: "fed_q96", text: "Yönetim kurulu, denetim kurulu, teknik kurul, disiplin kurulu karar defterleri noter tasdikli mi?", area: "Defterler ve Kayıtlar" },
        { id: "fed_q97", text: "Gelen-giden evrak kayıt defteri ve alındı-bilet defteri tutuluyor mu? Sayfa numaraları atlanmadan verilmiş ve her sayfa federasyon mührü ile mühürlenmiş mi?", area: "Defterler ve Kayıtlar" },
        { id: "fed_q98", text: "Defter kayıtları mürekkepli veya silinmeyen kalemle okunakli yapılıyor mu? Sayfalar koparılmamış, çizinti/kazıntı/silinti yok mu? Yanlışlıklar paraflanarak çizilmiş mi?", area: "Defterler ve Kayıtlar" },
        { id: "fed_q99", text: "Bilgisayar çıktısı şeklinde tutulan defterlerde tasdik beyaz A4 kağıtlarına yapılmış mı? Kararlar imzalandıktan sonra klasörde muhafaza ediliyor mu?", area: "Defterler ve Kayıtlar" },
        { id: "fed_q100", text: "Kulüp, sporcu, hakem, antrenör ve monitör kayıtları düzenli tutuluyor mu?", area: "Defterler ve Kayıtlar" },
        { id: "fed_q101", text: "Yurt içi-dışı faaliyet, kurs, seminer, sınav kayıtları ve verilen diploma, kuşak, millilik belgeleri kayıtları düzenli mi?", area: "Defterler ve Kayıtlar" },
        { id: "fed_q102", text: "Tüm hesaplara ilişkin ve faaliyet dönemini kapsayan ayrıntılı banka hesap ekstreleri muhafaza ediliyor mu?", area: "Defterler ve Kayıtlar" },
        { id: "fed_q103", text: "Genel Kurul dosyaları, Bakanlık/Genel Müdürlük yazışmaları ve Tahkim Kurulu yazışmaları dosyalanmış mı?", area: "Defterler ve Kayıtlar" },
        // ═══ 22) SAKLAMA (Yönerge Eki A - Madde 18) ═══
        { id: "fed_q104", text: "Defterlerin son kayıt tarihinden ve belgelerin düzenlenme tarihinden itibaren 10 yıl saklanması zorunluluğuna uyuluyor mu?", area: "Saklama ve Arşiv" },
        { id: "fed_q105", text: "Arşiv sorumlusu belirlenmiş mi? Arşiv sorumlusu değiştiğinde sayım yapılarak tutanak mukabilinde devir-teslim gerçekleştiriliyor mu?", area: "Saklama ve Arşiv" },
        { id: "fed_q106", text: "Devir-teslim tutanakları genel sekreter veya yetkilendirilen kişi tarafından onaylanmış mı?", area: "Saklama ve Arşiv" },
        // ═══ 23) SPORCU VE TEKNİK ELEMANLAR ═══
        { id: "fed_q107", text: "Sporcu, hakem ve antrenörlere ilişkin iş ve işlemler Bakanlık bilişim sistemi üzerinden yürütülüyor mu? İstatistiki bilgiler üç ayda bir Genel Müdürlüğe gönderiliyor mu?", area: "Sporcu ve Teknik Elemanlar" },
        { id: "fed_q108", text: "Müsabakalarda emniyet ve sağlıkla ilgili tedbirler ile 6222 sayılı Sporda Şiddet Kanunu kapsamındaki yükümlülükler yerine getiriliyor mu?", area: "Sporcu ve Teknik Elemanlar" },
        { id: "fed_q109", text: "Kendisine bağlı spor dallarında faaliyet gösteren spor kulüplerini ve spor anonim şirketlerini sportif yönden denetliyor mu?", area: "Sporcu ve Teknik Elemanlar" }
    ],
    kyk: [
        { id: "kyk_q1", text: "Asansörlerin periyodik kontrolü yapılmış mı? Periyodik kontrol raporları, Periyodik kontrol yapan firmanın yetki belgesi ve sözleşme?\nAsansörlerin periyodik kontrollerini, yılda en az bir defa, Sanayi ve Teknoloji Bakanlığı tarafından yetkilendirilen (TS EN ISO/IEC 17020) akredite A tipi muayene kuruluşu yapabilir. Periyodik kontrol, asansörün bakımını üstlenen yetkili firmanın nezaretinde gerçekleştirilir. Yetki belgesi, sözleşme.", area: "Asansör" },
        { id: "kyk_q2", text: "Asansörlerin her ay bakımı yapılıyor mu? Bakım sözleşmesini isteyelim. Bakımlara ilişkin evraklar.\nBakım sözleşmesinin birden fazla asansörü kapsaması durumunda, bakım hizmeti sunulacak her bir asansöre ait asansör kimlik numarası ve asansörün açık adresi bu sözleşmede belirtilir. Yetkili servis sözleşmesi noter huzurunda yapılır ve iki yılda bir yenilenir. Sözleşme bakım, onarım ve servis hizmetlerine ilişkin detayları içerir.", area: "Asansör" },
        { id: "kyk_q3", text: "Kurumdaki asansörlerin ruhsatı var mı? El Kitapçığı ve kayıt defteri bulunuyor mu?\nHer asansörle birlikte i) normal kullanım için gerekli olan plan ve şemaları içerecek şekilde bakım, muayene, tamir, periyodik kontroller ve kurtarma operasyonları ile ilgili bir el kitapçığı, ii) tamirlerin ve uygun görüldüğünde periyodik kontrollerin not edildiği bir kayıt defteri. Kayıt defterinin içeriği :piyasaya arz edilen asansörün beyan yükü, beyan hızı, tahrik türü, motor seri numarası ve gücü, halat ve/veya zincirler ile tip kontrol belgesi gerektiren aksam ve parçaların teknik özellikleri, tesis planları ve elektrik devre şemaları ile asansör periyodik kontrol sonuçları ve kazalar...", area: "Asansör" },
        { id: "kyk_q4", text: "Kırmızı etiketli asansörlerin kullanılmaması yurt idaresince sağlanmalıdır. 60 gün içinde eksiklikler tamamlanmalıdır.", area: "Asansör" },
        { id: "kyk_q5", text: "Sarı etiketli asansörlerin kullanılmaması yurt idaresince sağlanmalıdır. Eksikliklerinin en fazla 120 gün içinde giderilmesi gerekmektedir.", area: "Asansör" },
        { id: "kyk_q6", text: "Mavi etiketli asansör eksiklikleri bir sonraki periyodik kontrole kadar giderilmelidir.", area: "Asansör" },
        { id: "kyk_q7", text: "Asansör kabinlerinde çift yollu haberleşme ve sesli alarm donanımı var mı?\nKabinler, kurtarma hizmeti ile kalıcı irtibatı sağlayan çift yollu haberleşme ve sesli alarm donanımına sahip olmalıdır.", area: "Asansör" },
        { id: "kyk_q8", text: "Havalandırma sistemi çalışır durumda mı?\nKabinler uzun süreli durma halinde bile, yolcular için yeterli havalandırmayı temin edecek şekilde tasarlanır ve yapılır.", area: "Asansör" },
        { id: "kyk_q9", text: "Asansör kabininde azami yolcu sayısı ve kg değerinin yazılı mı?\nKabin taşınabilecek azami yolcu sayısı ile beyan yükünün kilogram değerini açıkça gösteren kolayca görülebilen bir plaka taşımalıdır.", area: "Asansör" },
        { id: "kyk_q10", text: "Asansör kabini dışında veya holünde \"Yangın sırasında kullanılmaz\" uyarısı var mı?\nAsansör kabini dışında asansör holünde, kolayca okunabilecek büyüklükte “YANGIN SIRASINDA KULLANILMAZ” levhasının olması zorunludur.", area: "Asansör" },
        { id: "kyk_q11", text: "Yangın tüpleri duvara (maks.90cm) asılı mı? Bakımları yapılmış mı? \nBakımı yapan üretici/servis firması dolum ve servis yeterlilik belgesine sahip olmalı. Tüplere yılda bir genel kontrol, 4 yılda bir dolum ve test yapılır.", area: "Yangın" },
        { id: "kyk_q12", text: "Binada duruma göre yangın uyarı butonu veya yangın algılama sensörü bulunmalıdır. Kontrolü yapıldı mı?", area: "Yangın" },
        { id: "kyk_q13", text: "Yangın merdiveni var mı? Uygunluk durumu? Yüzeye iniyor mu?\nKaçış yolları, bir yapının herhangi bir noktasından yer seviyesindeki caddeye kadar olan devamlı ve engellenmemiş yolun tamamıdır. (Kaçış yollarının çıkıştan sonraki kısımlarına dikkat edilmeli)", area: "Yangın" },
        { id: "kyk_q14", text: "Yangın merdivenini gören kamera var mı?", area: "Yangın" },
        { id: "kyk_q15", text: "Yangın merdiveni kapısı dışa doğru açılıyor mu? Önünde çıkışı engelleyecek engel var mı?\nDöner kapılar, turnikeler çıkış kapısı olarak kullanılamaz.\nYangın kaçış yollarında ve yangın merdivenlerinde engeller, kapılarda kilit, sürgü vb var mı?", area: "Yangın" },
        { id: "kyk_q16", text: "Yangın merdiveninde eşik var mı?", area: "Yangın" },
        { id: "kyk_q17", text: "Yangın merdiveni ışıklandırması yeterli mi?", area: "Yangın" },
        { id: "kyk_q18", text: "Acil çıkış uyarı levhası var mı? Sayıları yeterli mi? Doğru yönü gösteriyor mu?\nYönlendirme işaretleri; yeşil zemin üzerine beyaz olarak, ilgili yönetmelik ve standartlara uygun sembolleri ve normal zamanlarda kullanılacak çıkışlar için “ÇIKIŞ”, acil durumlarda kullanılacak çıkışlar için ise, “ACİL ÇIKIŞ” yazısını ihtiva eder.", area: "Yangın" },
        { id: "kyk_q19", text: "Jeneratör var mı uygun mu?", area: "Yangın" },
        { id: "kyk_q20", text: "Yangın çıkışları, çıkışa doğrudan erişim sağlıyor mu? (oda ve diğer mekanlardan geçilmeksizin çıkışa doğrudan erişilmelidir)\nBir yapıda veya katlarında bulunan her kullanıcı için, diğer kullanıcıların kullanımında olan odalardan veya mekanlardan geçmek zorunda kalmaksızın, bir çıkışa doğrudan erişim sağlanması gerekmektedir. (Uygunluğunu kontrol edelim)", area: "Yangın" },
        { id: "kyk_q21", text: "Yurdun en az iki çıkışı bulunuyor mu?\nBütün yapılarda, aksi belirtilmedikçe en az 2 çıkış tesis edilmesi ve çıkışların korunmuş olması gerekir.", area: "Yangın" },
        { id: "kyk_q22", text: "Kazan dairesi, yakıt deposu, sığınak, mutfak vb yerlerde yanıcı maddeler depolanıyor mu?\nBinaların yangın bakımından kritik özellikler gösteren, kazan daireleri, yakıt depoları, sobalar ve bacalar, sığınaklar, otoparklar, mutfaklar, çatılar, asansörler, yıldırımdan korunma tesisatı transformatör ve jeneratör gibi kısımlara yanıcı madde atılması ve depolanması yasaktır. Bu yerlerin belli aralıklarla temizlenmesi şart olup, bina sorumlusu bunu sağlamakla mükelleftir.", area: "Yangın" },
        { id: "kyk_q23", text: "Mutfak davlumbazında otomatik söndürme sistemi var mı? Ocaklarda gaz algılama sistemi ve gaz kesme tesisatı bulunuyor mu?\nMutfak davlumbazlarında otomatik söndürme sistemi yapılması ve ocaklarda kullanılan gazın gaz algılama, gaz kesme uyarı tesisatının kurulması şarttır.", area: "Yangın" },
        { id: "kyk_q24", text: "Yüksek binalar ile kapalı kullanım alanı 1000 m2’den büyük binalarda yangın tahliye projeleri itfaiyenin kolayca erişebileceği bir yerde bulunuyor mu?\nYüksek binalar ile kapalı kullanım alanı 1000 m2’den büyük binalarında, binaya yangın tahliye projeleri kolayca ulaşabilecek bir yerde bulundurulur.\n(Bu projelerde; binanın kaçış yolları, yangın merdivenleri, varsa itfaiye asansörleri, yangın dolapları, itfaiye su verme ağızları, yangın pompaları ile jeneratörün yeri işaretlenir.)", area: "Yangın" },
        { id: "kyk_q25", text: "21,5 m'den yüksek binalarda bina dışında açık merdivene izin verilmez.", area: "Yangın" },
        { id: "kyk_q26", text: "Acil durum ekipleri oluşturuldu mu? Evrakı?\n50'den fazla kişi bulunan binalarda acil durum ekipleri oluşturulur. (Söndürme ekibi, Kurtarma Ekibi, Koruma ekibi, İlk Yardım Ekibi)", area: "Yangın" },
        { id: "kyk_q27", text: "Doğal gaz ve elektriğin yangın, deprem anlarında otomatik devre dışı bırakacak sistemler bulunuyor mu?\nAfet durumlarında elektriğin ve doğalgazın kesilmesi can ve mal kaybının önlenmesi için gereklidir. Bu amaçla doğalgazın ve jeneratörün deprem ve yangın anına otomatik olarak devre dışı bırakacak sistemler bulunmalıdır.", area: "Yangın" },
        { id: "kyk_q28", text: "Kazan dairesi doğal gazlı ise doğal gaz sensörü aktif mi?", area: "Kalorifer" },
        { id: "kyk_q29", text: "Kazan dairesinin bakımı yapılıyor mu?", area: "Kalorifer" },
        { id: "kyk_q30", text: "Kazan dairesi kömürlü ise kömür depoları düzenli mi? Baca temizliği yapılıyor mu?", area: "Kalorifer" },
        { id: "kyk_q31", text: "Kazan dairesinde kuru kimyevi toz yangın söndürücü mevcut mu?\n En az 1 adet 6 kglık olması gerekir.", area: "Kalorifer" },
        { id: "kyk_q32", text: "Isı merkezlerinde bulunan basınçlı kapların test ve kontrolleri yapıldı mı? Belgeleri?", area: "Kalorifer" },
        { id: "kyk_q33", text: "Binaların yangın bakımından kritik özellikler gösteren, kazan daireleri, yakıt depoları, sobalar ve bacalar, sığınaklar, otoparklar, mutfaklar, çatılar, asansörler, yıldırımdan korunma tesisatı transformatör ve jeneratör gibi kısımlara yanıcı madde atılması ve depolanması yasaktır. Bu yerlerin belli aralıklarla temizlenmesi şart olup, bina sorumlusu bunu sağlamakla mükelleftir.", area: "Kalorifer" },
        { id: "kyk_q34", text: "Kazan dairelerinde duman bacalarına ilave olarak temiz ve kirli hava bacaları yaptırılması şarttır.", area: "Kalorifer" },
        { id: "kyk_q35", text: "Kazan dairesi kapısının kaçış merdivenine ya da genel kullanım merdivenlerine direkt açılmaması ve mutlaka bir güvenlik holüne açılması gerekir.", area: "Kalorifer" },
        { id: "kyk_q36", text: "Kazan dairesinde doğalgaz veya LPG kullanılması halinde bu gazları algılayacak gaz algılayıcıların kullanılması şarttır.", area: "Kalorifer" },
        { id: "kyk_q37", text: "Kazan dairesinde çalışan personelin ateşleyici belgesi bulunması gerekir", area: "Kalorifer" },
        { id: "kyk_q38", text: "LPG Kullanılan kazan dairelerinin bodrum katta bulunmaması gerekir", area: "Kalorifer" },
        { id: "kyk_q39", text: "LPG kullanılan kazan dairelerinde gaz algılayıcıların ortamdaki gaz kaçağını algılayıp uyarması ile devreye giren ve bina girişinde, otomatik emniyet vanası ve ani kapatma vanası gibi gaz kesme emniyet vanası bulunması gerekir.", area: "Kalorifer" },
        { id: "kyk_q40", text: "Yakıt ile ısınan yurtlarda akaryakıt depoları merdiven altına, boşluğuna, mutfağa banyoya ve yatak odalarına konulamaz.", area: "Kalorifer" },
        { id: "kyk_q41", text: "Sıvı ve katı yakıtlı kazanların bacalarının altında bir kurum temizleme menfezi bulunması ve yılda en az iki defa yetkili kişilere temizlettirilmesi gerekir.", area: "Kalorifer" },
        { id: "kyk_q42", text: "Küçük işletmeler yurt müdür yardımcısı veya nöbetçi personel tarafından hergün kontrol edilerek küçük işletmeler kontrol formuna işlenecektir. Tespit edilen eksiklikler işleticiye yazılı olarak tebliğ edilecektir.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q43", text: "İşletmeler yurt müdürü başkanlığında bir komisyon tarafından ayda en az iki defa denetlenecek ve forma işlenecektir. Eksiklikler işleticiye tebliğ edilecek ve süre verilerek düzeltilmesi sağlanacaktır.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q44", text: "İl Müdürlüğünce küçük işletmeler ayda bir kez denetlenecektir. Raporlar il müdürlüğünce tutulacaktır.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q45", text: "Bozuk olduğu tahmin edilen gıda maddelerinin satışı durdurulacak. İşletici itiraz ederse Tarım Bakanlığına tahlile gönderilecektir. Yurt müdürlüğü öğretim yılı içerisinde birkaç defa gıda maddelerinin tahlilini yaptırabilir.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q46", text: "Her gün yemeklerden sterilize kavanozlara veya çıtçıtlı poşetlere yemek numunesi alınacak 72 saat buzdolabında bekletilecek ve numuneler en az 300 gram olacaktır.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q47", text: "İşletici veya vekili lokanta kantin işletmesinde hazır bulunmak durumundadır.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q48", text: "Kapasitesi 501 ve üzeri olan yurtların lokanta işleticileri gıda mühendisi veya diyetisyen çalıştırmak zorundadır. (Bu kişiler vekil tayin edilemez.)", area: "Yemekhane ve Kantin" },
        { id: "kyk_q49", text: "Et ve et ürünlerinin menşei belgesi bulunacak, bu etlerin uygunluk raporları her alımda idareye teslim edilecektir. Menşei belli olmayan et balık tavuk ürünleri kabul edilmeyecek ve kullanılamayacaktır.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q50", text: "Paket et veya tavuk suyu, lezzet verici miks veya harçlar, yapay tatlandırıcı, glikoz şurubu, hazır çorba, hazır patates püresi, hazır köfte vb. fastfood ürünleri; çorba yemek tatlı yapımında kullanılmayacaktır.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q51", text: "İşletici, işletmede öğrencilerin sağlıklı ve dengeli beslenmesini sağlayıcı çeşitlilik ve yeterlilikte, hijyenik, ürün kalitesi ve besi değeri yüksek hizmet sunumunu sağlamakla yükümlüdür.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q52", text: "işletme yerlerinin tertip düzenine dikkat edilmemesi ve temizliğinin yapılmaması (19/a-1 yazılı ihtar cezası)", area: "Yemekhane ve Kantin" },
        { id: "kyk_q53", text: "işletici, vekili ve işletmede çalışan personelin kılık kıyafetinin uygun olmaması tırnaklarının uzun ve pis olması, saç sakalının kesilmemesi (19/a-1 yazılı ihtar cezası)", area: "Yemekhane ve Kantin" },
        { id: "kyk_q54", text: "İşletme yerlerinin boya badana ile kullanılan malzemelerin bakımına dikkat edilmemesi (19/a-1 yazılı ihtar cezası)", area: "Yemekhane ve Kantin" },
        { id: "kyk_q55", text: "Kapalı kutu veya ambalajda bulunması gereken malzemelerin açıkta bulunması ve böylece satışa arz edilmesi (19/a-1 yazılı ihtar cezası)", area: "Yemekhane ve Kantin" },
        { id: "kyk_q56", text: "Bulaşıkların bulaşık makinesinde yıkanmaması (19/a-1 yazılı ihtar cezası)", area: "Yemekhane ve Kantin" },
        { id: "kyk_q57", text: "Çatal kaşık bıçak gibi yemek hazırlama ve servisinde kullanılan malzemelerin paslanmaz çelik veya cam olmaması, kirli kırık paslı lekeli olması (19/a-1 yazılı ihtar cezası)", area: "Yemekhane ve Kantin" },
        { id: "kyk_q58", text: "Kahvaltılıklar ve yemekler porselen tabakla servis edilecektir. Tabaklar, tepsiler, çatal, kaşık, bıçak servisi eksiksiz ve temiz olacak, plastik malzeme kullanılmayacaktır.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q59", text: "İşleticiler, işletmelerde öğrencilerin kullanımına açık olmak üzere elektronik tartı aleti bulunduracaktır.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q60", text: "Son kullanma tarihi geçmiş ürünlerin satışta bulundurulması (19/a-1 yazılı ihtar cezası)", area: "Yemekhane ve Kantin" },
        { id: "kyk_q61", text: "Tüpgaz kullanılan yerlerde gaz tüplerinin işletme yerinde ve bakır borusuz kullanılması (19/b-7 para cezası)", area: "Yemekhane ve Kantin" },
        { id: "kyk_q62", text: "Mutfak ve kantinlerdeki çöp kovaları yeteri sayıda ve kapaklı olacaktır.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q63", text: "İşleticinin personelinin hijyen belgesi, aşçıların ise hijyen ve aşçılık belgesi olmalıdır.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q64", text: "İl Müdürlüğünce günün menüsü belirlenmesi adına komisyon kurulacaktır. Belirlenen günlük haftalık ve aylık menüler işleticiye tebliğ edilecektir.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q65", text: "Çay satışları kağıt bardakta olacak, köpük veya plastik bardaklar satışta kullanılmayacaktır", area: "Yemekhane ve Kantin" },
        { id: "kyk_q66", text: "Lokanta ve kantinlerin düzenli olarak ilaçlanıp ilaçlanmadığı kontrol edilmelidir.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q67", text: "Mutfak davlumbazlarında otomatik söndürme sistemi yapılması ve ocaklarda kullanılan gazın gaz algılama, gaz kesme uyarı tesisatının kurulması şarttır.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q68", text: "mutfakların bodrumda olması ve gaz kullanılması halinde havalandırma sistemi yapılır.", area: "Yemekhane ve Kantin" },
        { id: "kyk_q69", text: "Kızartmada kullanılmakta olan sıvı ve katı yağların kontrolü yapılıyor mu?\nKızartma yağı sıcaklığı (180 derece ve daha küçük)\nPolar madde (%25 ve daha küçük)\nAsit sayısı (2.5 ve daha küçük)", area: "Yemekhane ve Kantin" },
        { id: "kyk_q70", text: "Öğrenci odaları temiz mi?\nKat araları temiz mi?\nÇamaşır Makinesi ve kurutma makinesi sayısı yeterli mi ?", area: "Temizlik ve Güvenlik" },
        { id: "kyk_q71", text: "Su depoları (beton ise içi pvc anti bakteriyel mebran olmalı ya da paslanmaz çelik vb maddeden oluşmalı) gerekli temizlikleri yapılmalı ve bu belgelendirilmeli.", area: "Temizlik ve Güvenlik" },
        { id: "kyk_q72", text: "Yurtta güvenlik kamerası sistemi aktif mi? Kameraların yönü ve açısı uygun mu? En 30 gün kayıt yapabilecek bir kayıt sistemi var mı? Kamera sistemi ile izleme yapılan yerlere izleme yapıldığını belirtilen tabelalar asılmış mı?", area: "Temizlik ve Güvenlik" },
        { id: "kyk_q73", text: "Yurt çevresi kamera sistemi ile izleniyor mu?", area: "Temizlik ve Güvenlik" },
        { id: "kyk_q74", text: "Güvenlik vardiya çizelgesi ve vardiya defteri tutuluyor mu?", area: "Temizlik ve Güvenlik" },
        { id: "kyk_q75", text: "Nöbet kulübeleri düzenli mi?", area: "Temizlik ve Güvenlik" },
        { id: "kyk_q76", text: "Yurt çevresi istinat duvarları ile çevrili mi ? Çevre aydınlatması sürekli ve yeterli düzeyde mi?", area: "Temizlik ve Güvenlik" },
        { id: "kyk_q77", text: "Yurt binaları ve eklentilerine yaya ve araç giriş - çıkışları devamlı kontrol altında mı, güvenlik görevlisi sayısının yeterli mi? Öğrenci bavulları valizleri, tamir ve bakım için gelenlerin çantaları, yurda gelen gönderiler vb. xray veya el dedektörü ile kontrol edilyor mu?", area: "Temizlik ve Güvenlik" },
        { id: "kyk_q78", text: "Yurt bina ve eklentileri ile açık alanlarında haşerelerle mücadele için, izin belgesi bulunan kurum veya kuruluşlara yılda en az bir kez ilaçlatılır. (İzin belgesi ve kontrole dair belgeyi kontrol edelim)", area: "Temizlik ve Güvenlik" },
        { id: "kyk_q79", text: "Yurda tamir bakım için gelenler dahil tüm ziyaretçiler için bir ziyaretçi defteri tutuluyor mu?", area: "Temizlik ve Güvenlik" },
        { id: "kyk_q80", text: "Nöbet defteri elektronik ortamda tutuluyor mu? Nöbet bitiminde nöbetçi ve müdür yardımcısı tarafından imzalanıyor mu? \nNöbet defterine sistem üzerinden Özel ve Gece Hizmetleri Yönergesinin 10'uncu maddesinde sayılan (bina bölümleri, ısıtma, soğutma, aydınlatma, asansör sistemleri vd.) kontrollerin yapıldığı belirtilir.", area: "Temizlik ve Güvenlik" },
        { id: "kyk_q81", text: "Aylık nöbet çizelgesi düzenlenmiş mi? Çizelge il müdürü tarafından onaylanarak görevlendirme yapılmış mı?", area: "Temizlik ve Güvenlik" },
        { id: "kyk_q82", text: "Yurtta görevli kurum personeli, barınan öğrenciler ile küçük işletmeler ve hizmet alımı yoluyla yürütülen işlerde çalışanların kimlik bilgileri ilgili mercilere bildiriliyor mu?", area: "Temizlik ve Güvenlik" },
        { id: "kyk_q83", text: "Yurt için günlük, haftalık ve aylık temizlik planları yapılıyor mu? Bu planlara uyuluyor mu? “Yurt Temizlik Takip Çizelgesini alalım (Haftalık temizliklerde bulunması gerekir)", area: "Temizlik ve Güvenlik" },
        { id: "kyk_q84", text: "Öğrenciler özel eşyalarını dolaplarında muhafaza eder, bavul, valiz, çanta vb.yi valiz odalarına teslim eder. Dolap, bavul, valizlerde bozulabilecek yiyecek bulundurulmaz.", area: "Temizlik ve Güvenlik" },
        { id: "kyk_q85", text: "Öğrenci odalarında prizlerde ısıtma ve pişirme cihazları (su ısıtıcı, ütü, ocak vb.) kullanımına izin verilmez.", area: "Temizlik ve Güvenlik" },
        { id: "kyk_q86", text: "Elektrik, su, doğalgaz vb. tesisat ile su deposu, kuyular, kazan dairesi, yakıt deposu, doğalgaz depolama tankları ve jeneratörün bulunduğu yerler kontrol altında bulundurulur, bu mekânlara görevli personel dışında başkalarının girmesine izin verilmez.", area: "Temizlik ve Güvenlik" }
    ],
    ozel: [
        // ── KURUCU ve AÇILIŞ ──
        { id: "ozel_q1", text: "Kurumun kurum açma izni ile işyeri açma ve çalışma ruhsatı valilik tarafından verilmiş ve güncel mi?", area: "Kurucu ve Açılış" },
        { id: "ozel_q2", text: "Kurucu veya kurucu temsilcisinin mevzuatta aranan şartları (vatandaşlık, eğitim, adli sicil, yükümlülük yokluğu) taşıdığı belgelenmiş mi?", area: "Kurucu ve Açılış" },
        { id: "ozel_q3", text: "Tüzel kişilikle kurulan kurumda, en geç 1 yıl içinde tüzel kişiliğin oluşturulduğu ya da kurum devrinin yapıldığı kontrol edilmiş mi?", area: "Kurucu ve Açılış" },
        { id: "ozel_q4", text: "Kurucu temsilcisi değişikliği yapılmışsa; önceki denetimlerde idari para cezası ödenmesi ve yeni temsilcinin şartları taşıması koşulları yerine getirilmiş mi?", area: "Kurucu ve Açılış" },
        // ── PERSONEL ──
        { id: "ozel_q5", text: "Kurumda çalıştırılmak istenen tüm personel için il müdürlüğünden çalışma izni alınmış mı? Personel çalışma izninden önce göreve başlatılmamış mı?", area: "Personel" },
        { id: "ozel_q6", text: "Kurum müdürünün en az lisans mezunu olma şartını taşıdığı belgelenmiş mi? Müdür; kadın öğrencilere hizmet veren kurumda kadın, erkek öğrencilere hizmet veren kurumda erkek mi?", area: "Personel" },
        { id: "ozel_q7", text: "Kurum müdürü göreve başladıktan sonra Bakanlıkça düzenlenecek eğitim programına katılmış mı?", area: "Personel" },
        { id: "ozel_q8", text: "Yönetim personelinin tamamı göreve başladıktan itibaren 1 yıl içinde yetkili kuruluşlardan ilk yardım belgesi veya sertifikası almış mı?", area: "Personel" },
        { id: "ozel_q9", text: "Mutfak ve yemekhane personelinin işe başlama tarihinden itibaren en geç 3 ay içinde hijyen eğitim belgesi ve 10 gün içinde bulaşıcı hastalık olmadığına dair sağlık raporu alındığı kontrol edilmiş mi?", area: "Personel" },
        { id: "ozel_q10", text: "Katı, sıvı veya gaz yakıtlı merkezi kaloriferle ısıtılan kurumda yetki belgesi olan personel çalıştırılıyor mu? (Veya yetkili servisle bakım sözleşmesi yapılmış mı?)", area: "Personel" },
        { id: "ozel_q11", text: "Görevden ayrılan personel bilgileri 3 iş günü içinde il müdürlüğüne bildirilmiş mi?", area: "Personel" },
        // ── ÖĞRENCİ İŞLERİ ──
        { id: "ozel_q12", text: "Kurumda barınan öğrencilerin tamamı herhangi bir yükseköğretim kurumuna kayıtlı mı? Barınma şartlarını taşımayan öğrencilerin ilişiği kesilmiş mi?", area: "Öğrenci İşleri" },
        { id: "ozel_q13", text: "Her öğrenci için hizmet sunum taahhütnamesi düzenlenmiş ve bir örneği öğrenciye verilmiş mi?", area: "Öğrenci İşleri" },
        { id: "ozel_q14", text: "Yabancı uyruklu öğrencilerin öğrenci belgesi, pasaport örneği ve 3 ay içinde ikamet izin belgesi ibraz ettiği kontrol edilmiş mi?", area: "Öğrenci İşleri" },
        { id: "ozel_q15", text: "Kurumda barınan öğrenci sayısı hiçbir zaman kurum kapasitesini aşıyor mu? Geçici barınma birden fazla ay sürdürülmüş mü?", area: "Öğrenci İşleri" },
        { id: "ozel_q16", text: "Her öğretim yılı başında öğrencilerden güncel öğrenci belgesi istenmiş mi? Öğrenciliği sona erenlerin kurumla ilişiği kesilmiş mi?", area: "Öğrenci İşleri" },
        { id: "ozel_q17", text: "Öğrenci temsilcisi her öğretim yılı başında gizli oyla seçilmiş mi? Daha önce disiplin cezası almamış öğrenciler arasından mı seçilmiş?", area: "Öğrenci İşleri" },
        { id: "ozel_q18", text: "Üst üste iki ay barınma ücreti ödemeyen öğrencinin kurumla ilişiği kesilmiş mi?", area: "Öğrenci İşleri" },
        // ── BARINMA HİZMETLERİ ──
        { id: "ozel_q19", text: "Yurtlarda, pansiyonlarda ve apartlardaki öğrenci odalarında en fazla altı öğrenci barınıyor mu?", area: "Barınma Hizmetleri" },
        { id: "ozel_q20", text: "Barınma hizmetinin hangi tarihler arasında verileceği öğrencilere önceden duyurulmuş ve hizmet sunum taahhütnamesinde belirtilmiş mi?", area: "Barınma Hizmetleri" },
        { id: "ozel_q21", text: "Kurum binasındaki kantin, çamaşırhane gibi ortak hizmet yerleri kurum dışına mal ve hizmet satıyor mu? (Satış yasağına uyuluyor mu?)", area: "Barınma Hizmetleri" },
        { id: "ozel_q22", text: "Öğrenci odalarına siyasi pankart, bayrak ve sembol asılmasını engelleyici tedbirler alınmış mı?", area: "Barınma Hizmetleri" },
        { id: "ozel_q23", text: "Bina, ekipman ve tesisatın bakım, onarım ve kontrolleri düzenli olarak yapılıyor mu? Onarım tarihleri öğrencilere önceden duyuruluyor mu?", area: "Barınma Hizmetleri" },
        { id: "ozel_q24", text: "Kurum, açma izninde belirlenen amaç dışında kullanılıyor mu?", area: "Barınma Hizmetleri" },
        // ── BESLENME HİZMETİ ──
        { id: "ozel_q25", text: "Yurtlarda sabah kahvaltısı zorunlu olarak veriliyor mu? Beslenme hizmetinin kapsamı (öğle, akşam) hizmet sunum taahhütnamesinde belirtilmiş mi?", area: "Beslenme" },
        { id: "ozel_q26", text: "Beslenme hizmeti Bakanlıkça belirlenecek standartlara ve ilgili mevzuata uygun olarak gerçekleştiriliyor mu?", area: "Beslenme" },
        { id: "ozel_q27", text: "Mutfakta yemek yapılıyorsa aşçılar; Milli Eğitim/Kültür Bakanlığı onaylı aşçılık belgesi, mesleki yeterlilik belgesi veya ilgili eğitim programı katılım belgelerinden birine sahip mi?", area: "Beslenme" },
        // ── FİZİKİ STANDARTLAR ve GÜVENLİK ──
        { id: "ozel_q28", text: "Kurumun yangın merdivenleri, acil çıkış kapıları ve tahliye güzergahları açık, kullanılabilir ve engelsiz mi? 'Acil Çıkış' levhaları doğru yönü gösteriyor mu?", area: "Fiziki Standartlar ve Güvenlik" },
        { id: "ozel_q29", text: "Yangın söndürme tüplerinin bakımları yapılmış mı? (Yılda bir genel kontrol, 4 yılda bir dolum) Acil durum ekipleri oluşturulmuş mu?", area: "Fiziki Standartlar ve Güvenlik" },
        { id: "ozel_q30", text: "Güvenlik kameraları aktif mi? En az 30 gün kayıt kapasiteli kayıt sistemi mevcut mu? Kamera ile izleme yapılan yerlere bilgilendirme tabelaları asılmış mı?", area: "Fiziki Standartlar ve Güvenlik" },
        { id: "ozel_q31", text: "Kuruma giriş-çıkışlar kontrol altında mı? Ziyaretçi defteri tutuluyor mu?", area: "Fiziki Standartlar ve Güvenlik" },
        { id: "ozel_q32", text: "Isıtma ve havalandırma sistemleri çalışıyor mu? Kazan dairesinde yetki belgeli personel veya yetkili servis sözleşmesi mevcut mu?", area: "Fiziki Standartlar ve Güvenlik" },
        { id: "ozel_q33", text: "Ecza dolabı ve ilk yardım malzemeleri tam ve kullanılabilir durumda mı? Süresi geçmiş ilaç bulunuyor mu?", area: "Fiziki Standartlar ve Güvenlik" },
        { id: "ozel_q34", text: "Su depoları ve tesisat düzenli aralıklarla temizlettirilip belgelendiriliyor mu? Haşerelere karşı yılda en az bir kez ilaçlama yapılıyor mu?", area: "Fiziki Standartlar ve Güvenlik" },
        // ── İDARİ ve MALİ ──
        { id: "ozel_q35", text: "Kurumun aylık barınma ücreti il müdürlüğüne bildirilmiş mi? Öğrencilere uygulanan ücret bildirilen ücreti aşıyor mu?", area: "İdari ve Mali" },
        { id: "ozel_q36", text: "Kurum personelinin tamamı İş Kanunu kapsamında, SGK'ya bildirilmiş sözleşmeyle çalıştırılıyor mu?", area: "İdari ve Mali" },
        { id: "ozel_q37", text: "Öğrenci kayıt defterleri ve ilişkili belgeler güncel tutuluyor mu? İl müdürlüğünce istenen bilgi ve belgeler zamanında sunuluyor mu?", area: "İdari ve Mali" },
        { id: "ozel_q38", text: "Geçici barınanların okul ve kimlik bilgileri 3 iş günü içinde il müdürlüğüne bildirilmiş mi?", area: "İdari ve Mali" },
        { id: "ozel_q39", text: "Kurumun kapatılması ya da faaliyete ara verilmesi işlemlerinde en az 1 ay önce il müdürlüğüne, personele ve öğrencilere haber verilmiş mi?", area: "İdari ve Mali" },
        { id: "ozel_q40", text: "Kurum, Bakanlıkça belirlenen kalite standartlarına uygun hizmet sunuyor mu? Denetim sonucunda daha önce verilen idari para cezaları ödenmiş mi?", area: "İdari ve Mali" }
    ],
    spor: [
        // I- Kuruluş ve Tescil İşlemleri
        { id: "spor_q1", text: "Spor kulübünün, spor faaliyetlerine katılmak amacıyla gerçek veya tüzel en az yedi kişi tarafından kurulup kurulmadığı kontrol edilmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q2", text: "Kurucular tarafından imzalanmış kuruluş bildirimi ve gerekli belgelerin il müdürlüğüne eksiksiz sunulup sunulmadığı kontrol edilmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q3", text: "Kurucular tarafından her sayfası imzalanmış spor kulübü tüzüğünün bulunup bulunmadığı kontrol edilmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q4", text: "Spor kulübü tüzüğünde bulunması yasal olarak zorunlu asgari hususların yer alıp almadığı kontrol edilmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q5", text: "Kurucular arasında tüzel kişiliklerin bulunması halinde, bu tüzel kişilerin yetki kararları ve unvan belgelerinin tescil dosyasında yer alıp almadığı kontrol edilmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q6", text: "Kurucular arasında yabancı uyrukluların bulunması durumunda, Türkiye'de ikamet izinlerini gösteren belgelerin sunulup sunulmadığı kontrol edilmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q7", text: "Kamu kurum ve kuruluşları veya eğitim kurumları bünyesinde kurulan spor kulüpleri için ilgili kurumdan alınan resmi izin yazısının bulunup bulunmadığı kontrol edilmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q8", text: "Kurucu üyeler arasında mevzuat gereği kurucu olması mümkün olmayan/engelli kişilerin yer alıp almadığı denetlenmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q9", text: "Faaliyet gösterilen spor dallarının, bağlı bulunan spor federasyonları tarafından tescil edilip edilmediği kontrol edilmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q10", text: "İhtisas spor kulübü olarak tescil edilen kulübün en fazla iki spor dalında faaliyet gösterip göstermediği kontrol edilmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q11", text: "İhtisas spor kulübünün seçtiği spor dallarının bütün kategorilerinde faaliyette bulunup bulunmadığı denetlenmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q12", text: "İhtisas spor kulübünde, faaliyette bulunulan spor dalında en az üçüncü kademe antrenörlük belgesine sahip sözleşmeli antrenör çalıştırılıp çalıştırılmadığı kontrol edilmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q13", text: "İhtisas spor kulübünün ilgili spor dalıyla ilgili tapulu, tahsisli veya kiralanmış tesislerinin bulunup bulunmadığı (tesiste yürütülmesi zorunlu olmayan dallar hariç) denetlenmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q14", text: "İhtisas kulübü olma şartlarını kaybeden kulüplere eksikliklerini tamamlamaları için verilen sürenin sonunda şartların tamamlanıp tamamlanmadığı kontrol edilmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q15", text: "Kamu yararına çalışan spor kulübü statüsündeki kulübün aktif olarak faaliyette bulunup bulunmadığı denetlenmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q16", text: "Kamu yararına çalışan spor kulübünün faaliyet gösterdiği dallara uygun spor tesislerinin mülkiyetine, uzun süreli kiracılık veya tahsis hakkına sahip olup olmadığı kontrol edilmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q17", text: "Kamu yararına çalışan spor kulübünün en az üçü olimpik, paralimpik veya deaflimpik olmak üzere en az altı ayrı spor dalında faaliyette bulunup bulunmadığı denetlenmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q18", text: "İhtisas spor kulübü şeklinde kurulan kamu yararına çalışan kulübün olimpik spor dallarının dünya şampiyonalarına sporcu gönderip göndermediği veya faaliyette bulunup bulunmadığı denetlenmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q19", text: "Kamu yararına çalışan spor kulübünün faaliyet gösterdiği dalların en az birinde, ilgili spor federasyonunun düzenlediği en üst düzey spor faaliyetine katılıp katılmadığı kontrol edilmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q20", text: "Spor anonim şirketlerinin 6102 sayılı Türk Ticaret Kanunu'na göre kurulup kurulmadıkları ve tescil/faaliyet belgelerinin bulunup bulunmadığı denetlenmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q21", text: "Spor anonim şirketlerinin Gençlik ve Spor Bakanlığı nezdinde tescil işlemlerinin yapılıp yapılmadığı kontrol edilmiş mi?", area: "Kuruluş ve Tescil" },
        { id: "spor_q22", text: "Spor anonim şirketlerinin spor federasyonlarının faaliyetlerine katılabilmek için 7405 sayılı Kanunda öngörülen asgari sermaye zorunluluğunu yerine getirip getirmedikleri denetlenmiş mi?", area: "Kuruluş ve Tescil" },

        // 2- Spor Kulüplerinin Adları İle Spor Anonim Şirketlerinin Unvanlarına İlişkin İşlemler
        { id: "spor_q23", text: "Spor kulübü adlarının ve spor anonim şirket unvanlarının kanunun emredici hükümlerine, ahlaka, kamu düzenine ve kişilik haklarına aykırı olup olmadığı denetlenmiş mi?", area: "Ad ve Unvan" },
        { id: "spor_q24", text: "Kamu kurumları bünyesindeki spor kulüplerinin, bulundukları yer ile kurumun ismini taşıyıp taşımadıkları kontrol edilmiş mi?", area: "Ad ve Unvan" },
        { id: "spor_q25", text: "Spor kulüplerinin isimlerinin, diğer spor kulüpleri ile aynı veya ayırt edilemeyecek kadar benzer şekilde belirlenip belirlenmediği denetlenmiş mi?", area: "Ad ve Unvan" },
        { id: "spor_q26", text: "İsim değişikliklerinin Bakanlık izni ile yapılıp yapılmadığı ve değişiklikten sonra 1 yıllık süre geçmeden tekrar isim değişikliği talebinde bulunulup bulunulmadığı kontrol edilmiş mi?", area: "Ad ve Unvan" },

        // 3) Spor kulübünün tüzüklerinin, spor anonim şirketlerinin esas sözleşmelerinin ve bunların yönetim ve diğer organlarının tüzük veya esas sözleşmeye uygunluğuna ilişkin işlemler
        { id: "spor_q27", text: "Spor anonim şirketinin ticaret unvanında 'spor', 'sportif' veya belirli bir spor dalını tanımlayacak ibarelerden en az birinin yer alıp almadığı kontrol edilmiş mi?", area: "Tüzük ve Organlar" },
        { id: "spor_q28", text: "Spor anonim şirketinin esas sözleşmesinde işletme konusunun spor faaliyetlerini içerecek şekilde esaslı ve tanımlanmış olarak yer alıp almadığı denetlenmiş mi?", area: "Tüzük ve Organlar" },
        { id: "spor_q29", text: "Şirketin spor faaliyetlerinde kullanacağı renk, amblem ve benzeri diğer ayırıcı işaretlerin esas sözleşmede tanımlanıp tanımlanmadığı kontrol edilmiş mi?", area: "Tüzük ve Organlar" },
        { id: "spor_q30", text: "Şirketin faaliyette bulunmayı taahhüt ettiği spor dalları ile bu dallarda faaliyet gösterme hak ve yetkilerini içeren hükümlerin esas sözleşmede bulunup bulunmadığı denetlenmiş mi?", area: "Tüzük ve Organlar" },
        { id: "spor_q31", text: "Şirketin hesap döneminin, en yüksek harcamaya sahip spor dalındaki müsabaka dönemine göre esas sözleşmede belirtilip belirtilmediği kontrol edilmiş mi?", area: "Tüzük ve Organlar" },
        { id: "spor_q32", text: "Şirket bütçesinin hazırlanması, yürürlüğe konulması ve uygulanması usulü hakkında esas sözleşmede hüküm bulunup bulunmadığı denetlenmiş mi?", area: "Tüzük ve Organlar" },
        { id: "spor_q33", text: "Şirkette doğrudan veya dolaylı hakimiyeti bulunan spor kulübü lehine düzenlenen imtiyazların esas sözleşmede açıkça belirtilip belirtilmediği kontrol edilmiş mi?", area: "Tüzük ve Organlar" },
        { id: "spor_q34", text: "Spor kulübüyle bağlantılı spor anonim şirketinde, kâr payı dağıtımı ve bedelsiz sermaye artırımı hariç, kuruculara ve yönetim kurulu üyelerine menfaat sağlanmayacağına dair hüküm yer alıyor mu?", area: "Tüzük ve Organlar" },
        { id: "spor_q35", text: "Borsada işlem görenler hariç olmak üzere, bir spor kulübü ile bağlantılı olan spor anonim şirketlerinin paylarının nama yazılı olup olmadığı denetlenmiş mi?", area: "Tüzük ve Organlar" },
        { id: "spor_q36", text: "Payların %10'unu (halka açıklarda %5'ini) aşan veya hakimiyet devrine yol açan pay devirlerinin 15 gün içinde Bakanlığa bildirilip bildirilmediği kontrol edilmiş mi?", area: "Tüzük ve Organlar" },
        { id: "spor_q37", text: "Aynı ligde yer alan birden fazla spor kulübünde veya spor anonim şirketinde doğrudan veya dolaylı hakimiyeti bulunan gerçek veya tüzel kişilerin bulunup bulunmadığı denetlenmiş mi?", area: "Tüzük ve Organlar" },
        { id: "spor_q38", text: "Zorunlu ve ihtiyari organlarda görev yapan kişilerin, kasten işlenen suçlardan dolayı 1 yıl veya daha fazla süreyle hapis cezası veya yüz kızartıcı suçlardan mahkumiyetinin bulunup bulunmadığı denetlenmiş mi?", area: "Tüzük ve Organlar" },
        { id: "spor_q39", text: "Son 5 yıl içinde federasyonlar veya Bakanlık disiplin kurulları tarafından toplam 2 yıl veya tek seferde 1 yıl hak mahrumiyeti cezası almış kişilerin kurullarda görev alıp almadığı denetlenmiş mi?", area: "Tüzük ve Organlar" },

        // 4) Spor kulüpleri ve spor anonim şirketleri tarafından tutulması zorunlu defter ve kayıtlara ilişkin işlemler
        { id: "spor_q40", text: "Vergi Usul Kanunu, Türk Ticaret Kanunu ve ilgili yönetmelikler uyarınca tutulması gereken tüm zorunlu defterlerin eksiksiz tutulup tutulmadığı denetlenmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q41", text: "Tutulması zorunlu defterlerin sayfa açılış ve kapanış tasdiklerinin usulüne uygun şekilde yaptırılıp yaptırılmadığı kontrol edilmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q42", text: "Defter ve belgelerin yangın, hırsızlık ve kaybolmaya karşı güvenli bir şekilde muhafaza edilip edilmediği denetlenmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q43", text: "Defter kayıtlarının yasal süreler içerisinde ve muhasebe standartlarına uygun olarak doğru şekilde yapılıp yapılmadığı kontrol edilmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q44", text: "Elektronik ortamda tutulan defterlerin Bakanlıkça oluşturulan veya izin verilen yazılımlar kullanılarak tanzim edilip edilmediği denetlenmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q45", text: "Finansal tablolar (mizan, bilanço, gelir-gider tablosu) ile yevmiye/keber kayıtlarının ve muhasebe işlemlerinin birbiriyle uyumlu olup olmadığı denetlenmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q46", text: "Kulüp giderlerinin yasal mevzuata uygun harcama belgelerine (fatura, perakende fişi, serbest meslek makbuzu, gider pusulası vb.) dayandırılıp dayandırılmadığı kontrol edilmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q47", text: "Bedelsiz mal ve hizmet teslimlerinin seri numaralı Ayni Yardım Teslim Belgesi (Ek-5/A veya Ek-5/B) veya Ayni Bağış Alındı Belgesi ile yapılıp yapılmadığı denetlenmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q48", text: "Bastırılan ayni yardım/bağış belgelerinin adedi ile seri numaralarının 15 gün içinde matbaalar tarafından il müdürlüğüne bildirilip bildirilmediği kontrol edilmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q49", text: "Karar ve üye kayıt defteri gibi sürekli kayıtların ve diğer yasal hesap ve belgelerin 10 yıl süreyle saklanıp saklanmadığı denetlenmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q50", text: "Gelir tahsilatında kullanılan alındı belgelerinin yönetim kurulu kararı ile bastırılıp bastırılmadığı ve Alındı Belgesi Ciltleri Takip Defterinin tutulup tutulmadığı kontrol edilmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q51", text: "Gelir tahsil edecek kişilerin, yetki süreleri ve sınırları belirtilmek suretiyle yönetim kurulu kararı ile yetkilendirilip (Yetki Belgesi) yetkilendirilmediği denetlenmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q52", text: "Tahsil edilen paraların yasal süreler içinde (en geç 15 iş günü, banka limitini aşanlar için 2 iş günü) kulübün resmi banka hesabına yatırılıp yatırılmadığı denetlenmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q53", text: "İmzalanan sözleşmelerin asılları, teminat mektupları ve depozitoların muhasebe düzeninde Nazım Hesaplarda izlenip izlenmediği kontrol edilmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q54", text: "Stokların, demirbaşların ve diğer nakit kıymetlerin yılda en az bir kere sayılarak tutanak altına alınıp alınmadığı ve depo sorumlusunun belirlenip belirlenmediği denetlenmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q55", text: "Kasa ve banka kayıtları ile fiili nakit/mevduat mevcutlarının birbiriyle uyumlu olup olmadığı (mutabakat durumu) denetim tarihi itibarıyla kontrol edilmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q56", text: "Bilet basım, satış, gelir toplama ve hasılat paylaştırma işlemlerinin mevzuata uygun yürütülüp yürütülmediği ve doğru şekilde kayıtlara intikal ettirilip ettirilmediği denetlenmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q57", text: "Tüm muhasebe işlemlerinin muhasebe fişleri kesilerek yasal süreler içerisinde kayıtlara yansıtılıp yansıtılmadığı kontrol edilmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q58", text: "Kullanım ömrü 1 yıldan fazla olan demirbaş niteliğindeki malzemelerin doğrudan gider yazılmayıp aktifleştirilerek demirbaş defterine kaydedilip kaydedilmediği denetlenmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q59", text: "Depo giriş ve çıkışlarının (hurdaya ayırma, dağıtım vb.) yazılı ve imzalı tutanaklara istinaden yapılıp yapılmadığı ve düşümlerin anında defterden yapılıp yapılmadığı kontrol edilmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q60", text: "Bastırılan maç biletlerinin matbaacı imzalı tutanakla teslim alınıp Nazım Hesaplara girişinin yapılıp yapılmadığı ve güvenli yerde saklanıp saklanmadığı denetlenmiş mi?", area: "Defter ve Kayıtlar" },
        { id: "spor_q61", text: "Bilet satışlarına ilişkin Bilet Satış Tutanağı düzenlenip düzenlenmediği ve satış gelirlerinin bankaya yatırılmasına ilişkin usul ve talimatların bulunup bulunmadığı kontrol edilmiş mi?", area: "Defter ve Kayıtlar" },

        // 5) Bağlı Ortaklık Veya İştirak Niteliğindeki Spor Anonim Şirketleri Üzerinde Spor Kulübü Hakimiyetinin Varlığına İlişkin İşlemler
        { id: "spor_q62", text: "Belirli bir branşa ait aktif ve pasif varlıkları sermaye olarak şirkete devreden kulübün, şirket üzerinde doğrudan veya dolaylı hakimiyetinin bulunup bulunmadığı denetlenmiş mi?", area: "Bağlı Ortaklık ve İştirakler" },
        { id: "spor_q63", text: "Hakim kulüp lehine imtiyazlar hariç, diğer pay sahiplerine veya azınlığa TTK ve mevzuata aykırı imtiyazlar verilip verilmediği kontrol edilmiş mi?", area: "Bağlı Ortaklık ve İştirakler" },
        { id: "spor_q64", text: "Bir spor kulübüyle bağlantılı spor anonim şirketinde, kâr payı hariç kuruculara, yönetim kurulu üyelerine ve diğer kişilere menfaat sağlanıp sağlanmadığı denetlenmiş mi?", area: "Bağlı Ortaklık ve İştirakler" },
        { id: "spor_q65", text: "Aynı ligde yer alan birden fazla spor kulübünde veya spor anonim şirketinde doğrudan veya dolaylı hakimiyeti olan ortak gerçek/tüzel kişilerin bulunup bulunmadığı denetlenmiş mi?", area: "Bağlı Ortaklık ve İştirakler" },

        // 6) Birleşme Ve Mal Varlığının Devrine İlişkin İşlemler
        { id: "spor_q66", text: "Mevzuatta izin verilen başka bir kulübü devralarak birleşme dışında, kanuna aykırı bir birleşme işleminin bulunup bulunmadığı denetlenmiş mi?", area: "Birleşme ve Devir" },
        { id: "spor_q67", text: "Birleşme kararlarının, genel kurul üye tam sayısının en az 3/4'ünün katıldığı toplantıda, katılanların en az salt çoğunluğuyla alınıp alınmadığı kontrol edilmiş mi?", area: "Birleşme ve Devir" },
        { id: "spor_q68", text: "Aynı il sınırları dışında yer alan başka bir spor kulübüyle usulsüz birleşme yapılıp yapılmadığı denetlenmiş mi?", area: "Birleşme ve Devir" },
        { id: "spor_q69", text: "Birleşme işlemlerinde Bakanlık izninin bulunup bulunmadığı ve birleşmenin spor kulüpleri siciline tescil ettirilip ettirilmediği kontrol edilmiş mi?", area: "Birleşme ve Devir" },
        { id: "spor_q70", text: "Branşların aktif ve pasif varlıklarıyla devri kararının genel kurul üye tam sayısının en az 3/4'ünün katıldığı toplantıda salt çoğunlukla alınıp alınmadığı denetlenmiş mi?", area: "Birleşme ve Devir" },
        { id: "spor_q71", text: "Mal varlığı devri öncesinde gerekli raporların hazırlanarak Bakanlığa başvurulup başvurulmadığı ve onay işleminin yapılıp yapılmadığı kontrol edilmiş mi?", area: "Birleşme ve Devir" },
        { id: "spor_q72", text: "Şirketler arası veya şirketten kulübe yapılan mal varlığı devirlerinin, işlemin sonuçlanmasından itibaren 30 gün içinde Bakanlığa bildirilip bildirilmediği denetlenmiş mi?", area: "Birleşme ve Devir" },

        // 7) Spor Kulüpleri Ve Spor Anonim Şirketlerinin Finansal Tabloları Ve Yıllık Faaliyet Raporlarına İlişkin İşlemleri
        { id: "spor_q73", text: "Bünyesinde ticari işletme veya iştirak bulunduran kulübün, spor gelir/giderlerini Türkiye Muhasebe Standartlarına uygun konsolide finansal tablolarda raporlayıp raporlamadığı kontrol edilmiş mi?", area: "Finansal Raporlama" },
        { id: "spor_q74", text: "Konsolidasyona dahil kuruluşların finansal tablolarında yeknesak muhasebe politikalarının uygulanıp uygulanmadığı ve gerekli düzeltmelerin yapılıp yapılmadığı denetlenmiş mi?", area: "Finansal Raporlama" },
        { id: "spor_q75", text: "Konsolidasyon halinde, en yüksek harcamaya sahip spor dalı/şirketinin hesap döneminin spor kulübünün de hesap dönemi olarak kabul edilip edilmediği kontrol edilmiş mi?", area: "Finansal Raporlama" },
        { id: "spor_q76", text: "Farklı hesap dönemi kullanmak isteyen kulüplerin Bakanlıktan gerekli yazılı izinleri alıp almadığı denetlenmiş mi?", area: "Finansal Raporlama" },

        // 8) Spor Kulüpleri Ve Spor Anonim Şirkeleri Tarafından Düzenlenen Ve Bakanlığa Verilen Beyannamelere İlişkin İşlemleri
        { id: "spor_q77", text: "Beyannamenin, her yıl hesap dönemi bitiminden itibaren en geç üç ay içinde Bakanlığa (İl Müdürlüğüne) usulüne uygun şekilde verilip verilmediği denetlenmiş mi?", area: "Beyannameler" },
        { id: "spor_q78", text: "Beyanname verilerinin mevcut finansal tablolar, banka teyitleri ve cari mutabakatlar ile uyumlu olup olmadığı kontrol edilmiş mi?", area: "Beyannameler" },
        { id: "spor_q79", text: "Elektronik ortamda beyanname doldurma yetkisinin yönetim kurulu kararı ile verilip verilmediği ve yetkili değişikliklerinin 10 gün içinde bildirilip bildirilmediği denetlenmiş mi?", area: "Beyannameler" },
        { id: "spor_q80", text: "Kullanıcı kodu, şifre ve parolaların yetkisiz kişilerle paylaşılıp paylaşılmadığı ve çalınma/kayıp durumlarında il müdürlüğüne derhal bilgi verilip verilmediği kontrol edilmiş mi?", area: "Beyannameler" },

        // 9) Spor Kulüpleri Ve Spor Anonim Şirketlerinin Kanunun 18 İnci Maddesinde Yer Alan Temel Mali İlkeler İle Kanunun 20 inci Maddesinde Yer Alan Bütçe Ve Harcama İlkelerine Uyum Sağlayıp Sağlamadıklarına İlişkin İşlemleri
        { id: "spor_q81", text: "Mali imkanların geliştirilmesi, şeffaflık ve güvenilirliğin artırılması amacıyla vergi ve SGK yükümlülüklerinin süresi içinde yerine getirilip getirilmediği denetlenmiş mi?", area: "Bütçe ve Mali Sınırlar" },
        { id: "spor_q82", text: "Denk bütçe esasına ve giderlerin gelirler oranında gerçekleştirilmesini sağlayacak mali yapı kurallarına uyulup uyulmadığı kontrol edilmiş mi?", area: "Bütçe ve Mali Sınırlar" },
        { id: "spor_q83", text: "Bir bütçe yılında, önceki yıl brüt gelirlerinin %10'undan fazla yapılan borçlanmalar için gerekli nitelikli genel kurul onayının ve ek bütçe kararının alınıp alınmadığı denetlenmiş mi?", area: "Bütçe ve Mali Sınırlar" },
        { id: "spor_q84", text: "Ek bütçe ile yapılan toplam borçlanma miktarının, bir önceki yıl brüt gelirlerinin %50'sini aşıp aşmadığı kontrol edilmiş mi?", area: "Bütçe ve Mali Sınırlar" },
        { id: "spor_q85", text: "Tescilli olunan spor federasyonlarının ve uluslararası kuruluşların sportif, altyapı, personel, idari, hukuki ve mali kriterlerinin karşılanıp karşılanmadığı denetlenmiş mi?", area: "Bütçe ve Mali Sınırlar" },
        { id: "spor_q86", text: "Yönetim kurulu üyelerine, yakınlarına, çalışanlara veya ortaklara mevzuata aykırı şekilde hak ve alacak devri yapılıp yapılmadığı kontrol edilmiş mi?", area: "Bütçe ve Mali Sınırlar" },
        { id: "spor_q87", text: "Yönetim kurulu üyelerine, yakınlarına veya hakim ortaklara borç verilip verilmediği ya da bunlar lehine rehin, kefalet, ipotek gibi teminatlar sağlanıp sağlanmadığı denetlenmiş mi?", area: "Bütçe ve Mali Sınırlar" },
        { id: "spor_q88", text: "Yönetim kurulu üyelerinden veya yakınlarından alınan borçların borçlanma sınırlamalarının hesaplanmasında dikkate alınıp alınmadığı kontrol edilmiş mi?", area: "Bütçe ve Mali Sınırlar" },
        { id: "spor_q89", text: "Sporculara, kulüplere, spor anonim şirketlerine, federasyonlara veya kamu kurumlarına vadesi geçmiş borcun bulunup bulunmadığı denetlenmiş mi?", area: "Bütçe ve Mali Sınırlar" },
        { id: "spor_q90", text: "Kulübü veya şirketi kasıt veya ihmalle zarara uğratan başkan ve yönetim kurulu üyeleri hakkında sorumluluk davalarının açılıp açılmadığı ve zararların rücu edilip edilmediği denetlenmiş mi?", area: "Bütçe ve Mali Sınırlar" },

        // 10) Spor Kulüpleri Ve Spor Anonim Şirketlerinin Sona Ermesi Ve Tasfiyesine İlişkin İşlemleri
        { id: "spor_q91", text: "Tescil şartlarını kaybeden, organlarını kanuna aykırı oluşturan ve verilen 3 aylık ihtara rağmen düzeltmeyen şirketlerin tescillerinin iptal edilip edilmediği kontrol edilmiş mi?", area: "Sona Erme ve Tasfiye" },
        { id: "spor_q92", text: "Taahhüt ettiği spor dallarındaki faaliyetlere izinsiz ve mazeretsiz olarak üst üste 3 yıl katılmayan şirketlerin tescillerinin iptal edilip edilmediği denetlenmiş mi?", area: "Sona Erme ve Tasfiye" },
        { id: "spor_q93", text: "Feshedilen veya kendiliğinden sona eren kulübün para, mal ve haklarının tasfiye işlemlerinin tüzüğe uygun şekilde yürütülüp yürütülmediği kontrol edilmiş mi?", area: "Sona Erme ve Tasfiye" },
        { id: "spor_q94", text: "Tasfiye süresince yapılan tüm işlemlerde kulüp adında 'tasfiye halinde' ibaresinin kullanılıp kullanılmadığı denetlenmiş mi?", area: "Sona Erme ve Tasfiye" },
        { id: "spor_q95", text: "Mahkeme kararıyla feshine karar verilen veya tasfiyesi yapılamayan kulübün bütün varlıklarının il müdürlüğüne devredilip devredilmediği kontrol edilmiş mi?", area: "Sona Erme ve Tasfiye" },

        // 11) Mevzuat Gereğince Spor Kulüpleri Ve Spor Anonim Şirketleri Tarafından Gerçekleştirilen İşlemleri
        { id: "spor_q96", text: "Üyelik başvuruları, kabulleri ve üyelikten çıkarma işlemlerinin tüzük ve mevzuat hükümlerine uygun yürütülüp yürütülmediği denetlenmiş mi?", area: "Mevzuat ve Güvenlik" },
        { id: "spor_q97", text: "Genel kurul, yönetim kurulu ve denetim kurulu toplantılarının yasal sürelerde toplanıp toplanmadığı ve karar yeter sayılarına uyulup uyulmadığı kontrol edilmiş mi?", area: "Mevzuat ve Güvenlik" },
        { id: "spor_q98", text: "Personel işe alımı, özlük dosyalarının oluşturulması, SGK bildirimleri ve yasal hakların ödenmesi süreçlerinin mevzuata uygunluğu denetlenmiş mi?", area: "Mevzuat ve Güvenlik" },
        { id: "spor_q99", text: "Genel kurullarını elektronik ortamda gerçekleştiren kulüplerin altyapı yeterlilikleri ve gerekli izinleri alıp almadıkları kontrol edilmiş mi?", area: "Mevzuat ve Güvenlik" },
        { id: "spor_q100", text: "Bakanlık veya diğer kamu kurumlarınca tahsis edilen veya kiralanan taşınmazların amaca uygun kullanılıp kullanılmadığı ve bakımlarının yapılıp yapılmadığı denetlenmiş mi?", area: "Mevzuat ve Güvenlik" },
        { id: "spor_q101", text: "Sporcu menajerleriyle yapılan işlemlerin, sözleşmelerin ve ödemelerin TFF/Bakanlık mevzuatına uygun yürütülüp yürütülmediği denetlenmiş mi?", area: "Mevzuat ve Güvenlik" },
        { id: "spor_q102", text: "Sporcu ve antrenörlerle yapılan sözleşmelerin, lisans ve vize işlemlerinin ilgili federasyon talimatlarına uygunluğu kontrol edilmiş mi?", area: "Mevzuat ve Güvenlik" },
        { id: "spor_q103", text: "6222 sayılı Sporda Şiddet ve Düzensizliğin Önlenmesine Dair Kanun kapsamındaki güvenlik tedbirlerinin ve yükümlülüklerin yerine getirilip getirilmediği denetlenmiş mi?", area: "Mevzuat ve Güvenlik" },

        // 12) Spor Kulüpleri Ve Spor Anonim Şirketleri Organları Tarafından Gerçekleştirilen Diğer İşlemleri
        { id: "spor_q104", text: "İş sağlığı ve güvenliği, yapı güvenliği, işyeri açma ruhsatları gibi diğer kurumların yetki alanındaki yasal izinlerin mevcudiyeti ve geçerliliği denetlenmiş mi?", area: "Diğer İşlemler" },
        { id: "spor_q105", text: "Kulüp/şirket aleyhine açılan davalar, icra takipleri ve bunlara ilişkin ayrılan karşılıkların muhasebe kayıtlarındaki doğruluğu kontrol edilmiş mi?", area: "Diğer İşlemler" }
    ]
};
